### ISSUE TITLE
Readme import opensim error

### ISSUE THREAD

**Issue by aadimator** [stanfordnmbl/osim-rl#100]
In the Readme file, you specify the following instruction:

`If the command python -c "import opensim" runs smoothly, you are done! Otherwise, please refer to our FAQ section.`

I was wondering if it's a mistake on your part as I can't import the `opensim` package but `osim` package works just fine.

**Comment by spMohanty** [comment]
@aadimator : that would be the case if you don't have opensim installed. Did you set up the conda environment we released ? That should have opensim installed and ready to go.
