### ISSUE TITLE
example in the 'Basice Usage' step() getting slower as step count increases

### ISSUE THREAD

**Issue by immars** [stanfordnmbl/osim-rl#11]
Hello,

I installed and tried example in the README.md:

```
from osim.env import GaitEnv

env = GaitEnv(visualize=True)
observation = env.reset()
for i in range(500):
    observation, reward, done, info = env.step(env.action_space.sample())

```

but after about 200 steps the each step() call cost more than 1 second, and getting slower afterwards.

I add some simple logging and found that the time consumer  is:

```
self.osim_model.manager.integrate(self.osim_model.state)
```

in `osim.py`.

what might be the problem?

thanks,

**Comment by kidzik** [comment]
Hi immars,
first of all, sorry for the very late response.
Can you tell us more about your environment? (operating system, python version, CPU etc.)
Integration is indeed the most expensive step (that's where all the muscle forces, ground reaction forces and joint velocities are calculated) but it shouldn't take more than 1 second.
Thanks!

**Comment by kidzik** [comment]
I assume that the integration step can take significant time in certain environments, so I close this one for know as it is more related to https://github.com/opensim-org/opensim-core and https://github.com/simbody/simbody
