### ISSUE TITLE
Example forward integration does not set activations correctly

### ISSUE THREAD

**Issue by tomvanwouwe1992** [stanfordnmbl/osim-rl#12]
Hi,

I just starting looking into this project and installed everything. It looks very interesting to explore but I am running into a problem that I can't solve.
When I try to run a forward simulation with 'random' activations (suggested in the documentation on crowdAI), it seems that my model is not performing what it should do, as all the muscles stay unactivated and the model just drops down. I noticed that my action space was empty (box(0,)). I think this should not be happening so probably I am doing something wrong. I could solve it y adding the line self.reset() in the osim.py just before the action space and observation_space in the __init__ method. 
Now it seems to work for the first 3-4 integration steps. After that the model shows no activation and falls down.

Regards 
Tom

**Comment by kidzik** [comment]
Hi, we are actually moving to the newer version of OpenSim -- you probably downloaded the newest conda environment. Please try to use this branch https://github.com/stanfordnmbl/osim-rl/tree/nips with RunEnv as the environment. Sorry for the mess!
