### ISSUE TITLE
How to generate the video automatically?

### ISSUE THREAD

**Issue by adwardlee** [stanfordnmbl/osim-rl#123]
Hi,

I am trying some algorithms in the environment, and I want to generate videos to see the performance from the trained model.  When turning on the visualizer and click "View -> Save Movie" in the bottom left corner, it can record the frames. However, the camera cannot move with the body and it can only be controlled by the mouse.  Is there any ways to generate the video using python instead of manually clicking? Thanks.

Sincerely,

**Comment by spMohanty** [comment]
Hi @adwardlee ,
We use a forked version of simbody for the same : https://github.com/spMohanty/simbody/
If you build the above repo, and replace your current "simbody-visualizer" with the one from the new build, then it will write all the frames on every run into a folder specified by the env variable "CROWDAI_SUBMISSION_ID".

All the changes we did are in this file : https://github.com/spMohanty/simbody/blob/master/Simbody/Visualizer/simbody-visualizer/simbody-visualizer.cpp

its ugly, but it works. It would be great if simbody had a more programmatically transparent way to saving movies from runs 😢 ! Until then......


PS: I havent merged the latest changes from simbody (upstream), if you manage to play with it and pull in and merge all the changes from the simbody upstream, please do send a pull request.

**Comment by adwardlee** [comment]
Hi @spMohanty,  
Thanks for your quick reply.  I will check it out.
