### ISSUE TITLE
Setting and reading state off the Model

### ISSUE THREAD

**Issue by sebastiani** [stanfordnmbl/osim-rl#125]
I want to do model-based RL on this and one of the things I need is to calculate finite-differences from the model's dynamics. When I try to set the state as such:
```
delta = 0.0001
env = L2RunEnv()  
observation =  env.reset()  
perturbed_state = np.array(observation) + delta  
env.osim_model.set_state(perturbed_state)
```

I get the following error:

> ``TypeError: in method 'Manager_initialize', argument 2 of type 'SimTK::State const &``

Is this a bug in the implementation or do I have to pre-process my perturbed state vector before setting it in the model?

Thanks!

**Comment by kidzik** [comment]
The observation is just a function of the state and it does not contain the entire state of the model. You can get the state object by running `env.osim_model.get_state()`. The state is described here https://simtk.org/api_docs/simbody/3.5/classSimTK_1_1State.html. However, for the moment, unfortunately, there is no access through python to the State structure -- it is only accessible through C/C++ interface (@chrisdembia @carmichaelong please correct me if I'm wrong, thanks:)

**Comment by chrisdembia** [comment]
Actually, you do have access to the state in python. You can use `state.getY()` to get the values of all state variables (even in python).

**Comment by kidzik** [comment]
Thanks @chrisdembia ! @sebastiani I wrote a test/example on how you can access and modify the state (however it's a very naive modification) https://github.com/stanfordnmbl/osim-rl/commit/7ecae69c3cc8021455e3f9a3e207a2689e743929 
You can find details about the State variable in SimBody documentation.

**Comment by luisenp** [comment]
Thanks for the link here @kidzik. Is the internal open_sim state as returned by get_state() enough to restart another instance of the environment to the same point in the simulation? If I understand correctly, I can use methods such as `getU/setU`, `getY/setY`, `getUDot/setUDot`, etc. to serialize/deserialize the state. However, my concern is about the existence of other internal variables in the environment that would be necessary as well. Is this the case?

If this help, you can think of the following use case. I have my `env` at state `s` in machine A, and I want to create a copy of the environment in machine B, setting the new env's initial state to `s` and use to simulate a future trajectory there (expecting the same behavior, except for any random noise). 

Is setting all internal variables in `osim_model.state` enough to do this?

**Comment by kidzik** [comment]
@chrisdembia @carmichaelong is there a way to extract all state parameters at ones and make them serializable? Having them as a long fix-length vector should be enough

**Comment by luisenp** [comment]
Hi again. I mostly would like to confirm that the values of the state object (as returned by `OsimModel.get_state()`) are the only values needed to replicate an environment state in a different host/process. If so, serializing all state parameters and populating using `get/set` methods seems straightforward.

**Comment by carmichaelong** [comment]
Hi @luisenp, sorry for the delay. Indeed, what you get from the `get/set` methods should be exactly what is needed to replicate an environment state. Depending on what you need, you may want to also look into `state.getY()` as suggested previously in the thread too.
