### ISSUE TITLE
Spyder NOT working

### ISSUE THREAD

**Issue by MSShourijeh** [stanfordnmbl/osim-rl#126]
I have followed all the installation steps as in the readme.md file.

Everything worked smoothly.
Now, my question is about the Basic usage section: can I use spyder for this to execute 200 iterations? 

I tried, but I received an error message as "ModuleNotFoundError: No module named 'gym".
Conda does not include gym; do you know how I can add it?

I also followed the two options here: https://stackoverflow.com/questions/34217175/spyder-does-not-run-in-anaconda-virtual-environment-on-windows-10/34237461.

Both methods led to error due to the incompatibility of python version. Each one requires a library for spyder that cannot be installed, unfortunately.

What do you guys suggest for spyder's alternative?

As a MATLAB long time user, I was much more comfortable with spyder or anything alike.

**Comment by kidzik** [comment]
I've just tried to install spyder and it seems to work.

Please try in the console (assuming you followed steps from [Getting Started](https://github.com/stanfordnmbl/osim-rl#getting-started)):
```bash
source activate opensim-rl
pip install spyder
spyder3
```

Let me know if you get any errors after running `import opensim` in spyder
