### ISSUE TITLE
model with 2D and no prosthetic

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [stanfordnmbl/osim-rl#128]
https://github.com/stanfordnmbl/osim-rl#stepaction-project--true
The length of the vector is expected to be: 22 and 18 for 3D and 2D models without the prosthesis;

but I found that 2D model without the prosthesis need 22-dim vector action
my code:
```python
from osim.env import ProstheticsEnv
from tensorpack.utils import logger

env = ProstheticsEnv(visualize=False)
#env.change_model(model='2D', difficulty=0, prosthetic=False)
env.change_model(model='2D', difficulty=0, prosthetic=False)
observation = env.reset()
for i in range(2):
    act = env.action_space.sample()
    observation, reward, done, info = env.step(env.action_space.sample())
    logger.info("obs:{}   act:{}".format(len(observation), act.shape[0]))                                                             
```
output:
```python
 obs:167   act:22
```
Is it a bug here ? the action dim should be 18?

**Comment by kidzik** [comment]
That's a good point, we ended up leaving the actuators for compatibility and the only difference is that the model can fall sideways. I'll confirm that with the team and update the docs. (@carmichaelong is this the case?)

**Comment by carmichaelong** [comment]
This is true as long at the planar model is pointing to this file: [gait14dof22musc_planar_20170320.osim](https://github.com/stanfordnmbl/osim-rl/blob/master/osim/models/gait14dof22musc_planar_20170320.osim)

If so, then @kidzik is correct that the only difference is that the model cannot fall over sideways. Note that this does NOT mean the extra 4 muscles don't do anything. They have some (smaller) capacity to control the hip in the planar case still.
