### ISSUE TITLE
something about the state_desc

### ISSUE THREAD

**Issue by Ailsa1994** [stanfordnmbl/osim-rl#129]
I want to know the specific meaning of the features of state_desc, where can I get it?

**Comment by kidzik** [comment]
We are working on describing the details, it'll appear here http://osim-rl.stanford.edu/docs/nips2018/observation/

**Comment by kidzik** [comment]
Thanks for reporting. Yes, unfortunately, there is a bug in the center of mass. We will roll out the branch with the full observation of the center of mass.
https://github.com/stanfordnmbl/osim-rl/tree/ver2.1

We will also remove the observation vector and keep only the dictionary to avoid confusion. Projection is only an example and there are many issues with that (such as redundant values)

**Comment by Ailsa1994** [comment]
So, when changed the center of mass in observation, we have a 160-D observation?

**Comment by Ailsa1994** [comment]
In  osim.py, there gives a fixed value 158 when describe the observation space, but when changed the center of mass, there should be a 160-d observation, maybe they should be changed together.

**Comment by kidzik** [comment]
Sorry for the delayed answer. In the next release, we will skip the "projected" observation and only the dictionary will be available. Everyone can then can construct the observation vector on their own.
We will provide some examples though (close to what we get now with `project=True`). All in all, this ambiguity brings more confusion than value, while the dictionary response seems more useful.

**Comment by wangzhengfei0730** [comment]
Is there any plan for dictionary for action space? 
There is a clear explanation last year: http://osim-rl.stanford.edu/docs/nips2017/physics/, and I hope there will be one this year, because there are 4 new muscles now, I want to figure out what does them mean.
