### ISSUE TITLE
How to generate a video?

### ISSUE THREAD

**Issue by Jiayuan-Gu** [stanfordnmbl/osim-rl#13]
We are trying the code on Ubuntu, and we managed to generate videos for gym games like CartPole and Atari games by run 'xvfb-run' (Because the display is based on Xvnc).
We used Monitor wrapper to generate videos, but in the 'osim.py':
```
metadata = {
     'render.modes': ['human'],
     'video.frames_per_second': 50
}
```
However, 'video_recorder' requires render.modes to be 'rgb_array' or ‘ansi'.  Does anyone know how to generate a video? Thx

**Comment by kidzik** [comment]
Hi, opensim visualizer is not compatible with visualizers from OpenAI. One simple way to generate a video is to turn on the visualizer and click "View -> Save Movie" in the bottom left corner. A set of frames will be recorded and you can create a mp4 using ffmpeg.

**Comment by Jiayuan-Gu** [comment]
@kidzik
Thanks for replying. We could display the visualizer on a PC; however, it did not work for a server if using VNC. It would raise an error related to SimTK:
```
RuntimeError: std::exception in 'bool OpenSim::Manager::integrate(SimTK::State &,double)': SimTK Exception thrown at VisualizerProtocol.cpp:378:
  Error detected by Simbody method VisualizerProtocol: An attempt to write() 1 bytes to pipe 4 failed with errno=32 (Broken pipe).
  (Required condition 'status!=-1' was not met.)
```
I think I might turn to opensim repository to see if there is any solution to visualizing on a server with vnc and try to fix this problem by checking the corresponding cpp.

**Comment by kidzik** [comment]
I suppose it can be this issue https://github.com/simbody/simbody/issues/550 and it seems not resolved yet. Normally it works if you restart the environment.
In your case I one temporary solution could be to save the model that you have trained and then run it on a PC.
