### ISSUE TITLE
Crossing legs - no collision 

### ISSUE THREAD

**Issue by Frawak** [stanfordnmbl/osim-rl#130]
I accidentally submitted this: https://www.crowdai.org/challenges/31/submissions/9380

As you can see, the right leg went through the standing left one. In (future) 3D scenarios this may become an issue and could yield unwanted results even if the reward is good (theoretically). 

I know, the physics of this model is slow but is there any plan to address collision within the body?

**Comment by kidzik** [comment]
This was a conscious choice for simplifying the model. We will design the objective in such a way that the leg-crossing will be suboptimal.
Thanks for reporting, this already raised some confusion, so we will update the docs.
