### ISSUE TITLE
Crash on submission, server returns 502 Server Error: Bad Gateway for url

### ISSUE THREAD

**Issue by mattiasljungstrom** [stanfordnmbl/osim-rl#136]
I've submitted with the exact same client side code before and it worked yesterday. Only difference is the model has been further trained.

HTTPError: 502 Server Error: Bad Gateway for url: http://grader.crowdai.org:1729/v1/envs/2332___2208cbbc40/step/

This happens after 147 steps on episode 1.

**Comment by mattiasljungstrom** [comment]
I trained my model for a single episode, creating a slight tweak in weights and now the submission works again. It seems like it's related to a bad state in the server side simulation?

**Comment by definitelyuncertain** [comment]
Sorry I don't have a solution, just confirming that I am also facing this issue. I get the Bad Gateway error at 125 steps consistently. Further more, it finishes without error when I submit random actions.

On closer inspection, 125 is around how many steps my model lasts per episode when I run it locally (and of course, my local version of the simulator doesn't crash).

**Comment by spMohanty** [comment]
@definitelyuncertain @mattiasljungstrom : If you can deterministically replicate this, then it would be quite helpful if you can provide us details on how we can try it out.
Would it be possible for you to create a private repository of your code at [https://gitlab.crowdai.org](https://gitlab.crowdai.org) and send us the link to the same ?
Or please ping us when you are online on the gitter channel, and we can try to debug it together.
Thanks

**Comment by kidzik** [comment]
@spMohanty what's the status on this and https://github.com/stanfordnmbl/osim-rl/issues/146 ?
It seems many solutions go through, but there are still quite a few errors. Let me know how I can help (or where to start with debugging this one).
