### ISSUE TITLE
DLL load failed when I run the command   python -c "import opensim"

### ISSUE THREAD

**Issue by Agtiger** [stanfordnmbl/osim-rl#140]
![err](https://user-images.githubusercontent.com/20347594/42622790-ceb02f52-85f3-11e8-9913-fe7c1fed4d1d.png)
The Opensim-rl has been installed successfully.However,when I run the command  python -c "import opensim",something goes wrong (see pic).Could you please provide me some advice?

**Comment by kidzik** [comment]
Which windows are you using? can you please send us the output of `conda list`?
Thanks!

**Comment by Agtiger** [comment]
Thanks for your reply!
windows 7(64) My conda lists are as following.
![image](https://user-images.githubusercontent.com/20347594/42722005-df3823d2-8776-11e8-90a9-1d27916a9eb1.png)
![image](https://user-images.githubusercontent.com/20347594/42722007-eb028090-8776-11e8-8c24-b10e02a9c2f4.png)
![image](https://user-images.githubusercontent.com/20347594/42722010-f9addc52-8776-11e8-8700-f097328e740d.png)
![image](https://user-images.githubusercontent.com/20347594/42722011-02d244a8-8777-11e8-9dc2-6bce2d9e3b17.png)
Thanks !

**Comment by kidzik** [comment]
I've just tried to install everything on a clean windows 10 instance and it seems to look like this
![screenshot 2018-08-02 19 29 53](https://user-images.githubusercontent.com/981858/43606431-2e4b5b46-9650-11e8-933d-2d89268ada70.png)

One note is that I haven't managed to make it work with PowerShell. Besides that it seems to be working
