### ISSUE TITLE
Is it possible to install the environment without create a specific conda env?

### ISSUE THREAD

**Issue by wangzhengfei0730** [stanfordnmbl/osim-rl#144]
I am trying to deploy cluster for this challenge using Docker. However, it seems that there is only one specific approach to install the environment: to create a conda env, which is not meeting my expectation.
So I'd like to know, is it possible to install the environment without create the specific conda env, named opensim-rl? Can I install this challenge environment by simply pip, or conda install <some-package>?

**Comment by modanesh** [comment]
Are there any workarounds for that?

**Comment by kidzik** [comment]
Yes, you can install it with PIP. You'll just need to have [OpenSim](https://github.com/opensim-org/opensim-core) compiled and installed with python wrappers.
