### ISSUE TITLE
HTTPError: 504 Server Error: Gateway Time-out for url on server

### ISSUE THREAD

**Issue by adwardlee** [stanfordnmbl/osim-rl#146]
Hi @kidzik @spMohanty ,

When I submit my action to the server, it can get stuck at some certain states and there is no nan in my action. However, it can run at my local machine. Thanks.

Sincerely,

**Comment by mattiasljungstrom** [comment]
Having the same issue today. My current model is very slow on some steps when I run it locally. (It pushes hard on the ground.)

HTTPError: 504 Server Error: Gateway Time-out for url: http://grader.crowdai.org:1729/v1/envs/2332___7390fed067/step/
