### ISSUE TITLE
NameError: name 'RunEnv' is not defined

### ISSUE THREAD

**Issue by ViktorM** [stanfordnmbl/osim-rl#15]
After following instructions for Windows 10 install RunEnv can't be imported:
```
>>> from osim.env import RunEnv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name RunEnv
```
While import of the GaitEnv is working but running with the visualization don't:

```
RuntimeError: std::exception in 'SimTK::State & OpenSim::Model::initSystem()': SimTK Exception thrown at VisualizerProtocol.cpp:163:
  Error detected by Simbody method VisualizerProtocol::ctor(): Unable to spawn executable 'simbody-visualizer' from directories:
  c:\Users\Viktor\Anaconda3\envs\opensim-rl\
  C:\Users\Viktor\Anaconda3\envs\opensim-rl/Library/simbody/bin/Final system error was errno=2 (No such file or directory).
```

**Comment by kidzik** [comment]
GaitEnv shouldn't be there anymore. Please check if you have the newest version of osim-rl installed.
   
    pip install git+https://github.com/stanfordnmbl/osim-rl.git --upgrade

should do the job.

**Comment by ViktorM** [comment]
Yes it should have been the case that I had an older version installed. It can be useful to add your --ugrade advice to the docs. Can't test your recommendation as I've already deleted the environment and tried installing from scratch but hit another error:
```
C:\Users\Viktor>conda create -n opensim-rl -c kidzik opensim git
Fetching package metadata .............
Solving package specifications: .
PackageNotFoundError: Package not found: '' Dependency missing in current win-64 channels:
  - opensim -> freeglut
```
As a result environment opensim-rl hasn't been created.

**Comment by kidzik** [comment]
Does

    conda install -c conda-forge freeglut

help?

**Comment by ViktorM** [comment]
The same result:

```
The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0      conda-forge
    freeglut:  3.0.0-vc14_4 conda-forge [vc14]

The following packages will be UPDATED:

    conda:     4.2.9-py35_0             --> 4.2.13-py35_0 conda-forge

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.6. 100% |###############################| Time: 0:00:00 187.36 kB/s
freeglut-3.0.0 100% |###############################| Time: 0:00:01 227.32 kB/s
conda-4.2.13-p 100% |###############################| Time: 0:00:01 313.00 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

D:\Stanford\Deep_RL\rllabplusplus\sandbox\rocky\tf\launchers>conda create -n opensim-rl -c kidzik opensim git
Fetching package metadata .............
Solving package specifications: .


PackageNotFoundError: Package not found: '' Dependency missing in current win-64 channels:
  - opensim -> freeglut

You can search for packages on anaconda.org with

    anaconda search -t conda freeglut
```
But it shouldn't work in any case as py35 version will be installed. Installation should be done inside py27 newly created env, but it wasn't created due to the error in message above.

**Comment by kidzik** [comment]
I copied freeglut from conda-forge to the channel https://anaconda.org/kidzik/freeglut so now conda should be able to find it. Can you check if

    conda create -n opensim-rl -c kidzik opensim git

works?

**Comment by ViktorM** [comment]
No environment has been created and I moved further. I met an error only during the last installation step:
```
(opensim-rl) C:\Users\Viktor>pip install git+https://github.com/stanfordnmbl/osim-rl.git
Collecting git+https://github.com/stanfordnmbl/osim-rl.git
  Cloning https://github.com/stanfordnmbl/osim-rl.git to c:\users\viktor\appdata\local\temp\pip-v95pvw-build
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.

(opensim-rl) C:\Users\Viktor>
(opensim-rl) C:\Users\Viktor>pip install setuptools
Requirement already satisfied: setuptools in c:\users\viktor\anaconda3\envs\opensim-rl\lib\site-packages\setuptools-27.2.0-py2.7.egg
```

**Comment by kidzik** [comment]
According to this https://github.com/ContinuumIO/anaconda-issues/issues/542 the following should work

    pip install -U --ignore-installed setuptools

Thanks for checking!

**Comment by ViktorM** [comment]
No it's working, thanks! Simulation has started and the model falled. But in different way then in the gif - it falled backward from the square he was standing and hinge with the balls stuck on the ground level and trunk and head down, below the ground level. Is this expected?

**Comment by kidzik** [comment]
Excellent! Thanks a lot for testing it on Windows!
Yes, the gif is a bit outdated so it might not reflect the actual behavior.
Hanginig upside down is expected when actions are taken after `done == True`. Indeed it's not intuitive we may throw some error instead. I will close this issue though since the installation works.

**Comment by akhilsanand** [comment]
Hi @ViktorM @kidzik 
I am getting the same error "ImportError: cannot import name RunEnv" on MacOSX and tried your the advised solution to update osim-rl version but it still not working.

I am using anaconda with python 2.7

Regards,
Akhil
