### ISSUE TITLE
skeleton passes through the floor when running L2RunEnv

### ISSUE THREAD

**Issue by JoyChopra1298** [stanfordnmbl/osim-rl#150]
When I followed the steps provided here http://osim-rl.stanford.edu/docs/quickstart/ , the skeleton goes through the floor instead of colliding with it.
Why is this happening? Is there a problem with the meshes?

**Comment by kidzik** [comment]
By design, we only have contact model in feet for this model (to simplify the computations). This won't change any time soon (as it's not that crucial for modeling walking).
