### ISSUE TITLE
skeleton going through floor for ddpg.keras-rl.py

### ISSUE THREAD

**Issue by JoyChopra1298** [stanfordnmbl/osim-rl#152]
As visible in the screenshots below the skeleton isn't rendering properly. Is there some issue with the underlying osim file?

![skeleton head above the floor](https://user-images.githubusercontent.com/27682820/43360755-a764daee-92da-11e8-9a51-9bcc4f12e430.png)
![rest of the body is below the floor](https://user-images.githubusercontent.com/27682820/43360756-b363599c-92da-11e8-8986-debffe5f2d03.png)

**Comment by kidzik** [comment]
That's a recent change in OpenSim. For now, please change the view to the black background (ground is irrelevant in this example). There is an updated model, we need to port, thanks for catching that.
