### ISSUE TITLE
opensim version

### ISSUE THREAD

**Issue by atypic** [stanfordnmbl/osim-rl#157]
Hi,

which version/tag of opensim is osim-rl expected to run against? 

I've tried the latest as of today, but it seems osim-rl uses some "setIntegratorAccuracy" that I can't find in the python wrappers created by the newest opensim versions.

thanks

**Comment by kidzik** [comment]
We are using a conda build with this params
https://github.com/stanfordnmbl/staged-recipes/blob/master/recipes/opensim/meta.yaml
so more precisely, we are using this 'patched' version of opensim
https://github.com/kidzik/opensim-core/tree/550c2a15d56a918f5fe712d4050b8b5eba84eaeb
where the patch is exactly for exposing the `setIntegratorAccuracy` function
