### ISSUE TITLE
random_seed is not set in def change_model() of class ProstheticsEnv(OsimEnv)

### ISSUE THREAD

**Issue by huschen** [stanfordnmbl/osim-rl#158]
Though stated in the [document of interface.](http://osim-rl.stanford.edu/docs/nips2018/interface/) 

> seed - starting seed for the random number generator. If the seed is None, generation from the previous seed is continued.
 
and here is the [source code](https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/osim.py##L419-L422):

    def change_model(self, model='3D', prosthetic=True, difficulty=0, seed=None):
        if (self.model, self.prosthetic) != (model, prosthetic):
            self.model, self.prosthetic = model, prosthetic
            self.load_model(self.model_paths[self.get_model_key()])
seed is not set.

**Comment by kidzik** [comment]
Thanks for catching that. There is no stochasticity in the first round, but there will be in the second round https://github.com/stanfordnmbl/osim-rl/issues/159 and the seed will become relevant

**Comment by huschen** [comment]
I am trying to see if it is possible to make the training deterministic.
Is there any non-deterministic introduced by OpenSim environment? Any known computations (besides GPU computation)? Any other random seeds to be set besides the following?

     tf.set_random_seed(x)
     np.random.seed(x)
     random.seed(x)

Cheers.

**Comment by kidzik** [comment]
I suppose there might be potentially some stochasticity in sampling for the integrator. @carmichaelong is there any stochasticity on the OpenSim side during forwarding simulations?

**Comment by carmichaelong** [comment]
There shouldn't be any stochastic events during integrations.

**Comment by kidzik** [comment]
Thanks, @carmichael.
@huschen closing, for now, let us know if you experience any nondeterministic behavior.
