### ISSUE TITLE
Question about evaluation in Round 2 

### ISSUE THREAD

**Issue by yobobobo** [stanfordnmbl/osim-rl#159]
# Round 2
In the second round the task is also to follow a requested velocity vector. However, in this round the vector will change in time and it will be a random process. We will provide the distribution of this process in mid-July.

Is there any more information about Round 2?
- How long will the robot be evaluated in round2? 1000 steps like last year or 300 steps in round1?
- Could you classify **"in this round the vector will change in time"**? Will the robot be given a new target vector and restart from the starting point(with stand posture)?or Will the robot be given a new target vector after running some steps and go on?(e.g. 300steps with target 0.1m/s, and then 300 steps with target 0.5m/s, then 0.2m/s for another 300 steps)

**Comment by yobobobo** [comment]
@kidzik Thanks for your quick reply!
Another mirror questions:  
Is the rotation/velocity in 3d model using the same metric unit as 2d(challenge in 2017)? 
I want to try some imitation learning to learn from last year's model but not confirm they are using the same metric unit.

**Comment by kidzik** [comment]
Yes, the rotation of the pelvis is still in radians with the same 0 angle.

**Comment by kidzik** [comment]
Yes, the only difference is that now it can also move sideways -- there are two more rotations and one more transactional dimensions.

**Comment by yobobobo** [comment]
Thanks for your detailed reply.

**Comment by yobobobo** [comment]
@kidzik Hi, any development about round2 this week? I haven't seen any information new in github or crowdai
