### ISSUE TITLE
Make 3.5+ the main supported version of the Python for the challenge

### ISSUE THREAD

**Issue by ViktorM** [stanfordnmbl/osim-rl#16]
Hi,

I'd like to suggest to make Python 3.5.2, not 2.7 the main used version for the challenge. Python 2.7 is quit old and obsolete version, all the main deep learning frameworks are supporting 3.5 and even 3.6+ for quit a long time. Moreover some of standard RL libraries like rllab: https://github.com/openai/rllab or the new baselines are officially supported only Python 3.5+: https://github.com/openai/baselines/blob/master/setup.py 

So I suppose there are no serious reason to make Python 2.7 the main supported version for the challenge directed toward the future. Moreover if Linux users have some choice, making 2.7 the main supported version blocks almost any chance of running osim-rl on Windows and instructions for Window installation won't make a lot of sense as on Windows 10 TensorFlow support only Python 3.5.2. And probably the support of the 3.6 will be added soon. As a result Keras-RL with TensorFlow backend won't be working at all.

May be not only for me it'll be more convenient to do development and testing of already trained agents on Windows but train on Linux PC's. 

Best regards,
Viktor

P. S. And even on my Ubuntu PC all the DL and RL libraries that I plan to use were already installed and set in the Python 3.5+ environment. It will be much more convenient if Osim-RL can be be used in already set and tested environment too.

**Comment by kidzik** [comment]
This is definitely something on the roadmap. For now, we will probably provide a docker container with tensorflow, keras and python 2.7 for windows users. If you can contribute a conda build with 3.5 it will be definitely very appreciated.

**Comment by ViktorM** [comment]
I'll take a look into conda build for 3.5 this weekend. 

As about docker build for Windows it won't support GPU acceleration and in general makes things harder compare to the plain 3.5 installation.  I understand that it is hard to support and test environment for different version of Python and different OS, but my main point was that by default 3.5+ should be used. There can be no 2.7 version for challenge at all or it can be add by the request if somebody required it, but the main should be 3.5+.

It will make support easier. It allows using standard and widely adapted Deep RL libraries like rllab to start with. No dockers for Windows will be needed  and installation will be simple and work out of the box. Python 3.5 is almost 2 years on the market, and a lot of colleagues and people in DL community  are using it for quite a long time. It's not representative but I don't no anyone who is using Python 2.7.  So I suppose there will be a lot participants of the challenge for whom using 2.7 installation will be a pain too.

Moreover support of the 2.7 requires a lot of time and efforts but it has no future in opposite to the 3.5+ one. Neither Python 2.7 itself nor the installation of osim-rl created. I suppose one of the goals of the challenge will be to encourage further research and applications of RL to biomechanics with OpenSim. It's almost for sure  2.7 won't be used for their research especially if will be using rllab, baselines or the roboschool: https://github.com/openai/roboschool It also supports only Python 3.+ how I can conclude from the installation guide.

P. S. Btw in can be interesting idea to add few Opensim environments with different task for training in the Roboschool or it's fork in future.

**Comment by chrisdembia** [comment]
To use Python 3, it will be necessary for OpenSim's Python wrapper to be compiled using Python 3. There is an open PR for this (https://github.com/opensim-org/opensim-core/pull/1733), but it has not yet been merged into OpenSim's master branch.

OpenSim currently has a PR for supporting Python 3 but it is not yet merged.

**Comment by ViktorM** [comment]
I see, thanks. I suspected that there were some serious reason behind not having 3.5 at the moment. Hope it'll be merged soon and I can help with creating 3.5 conda environment for the challenge.

**Comment by chrisdembia** [comment]
I am unfamiliar with the `osim-rl` code base so I don't know what is required to support 3.5.

But the Python bindings for OpenSim must be compiled with the same Python version you plan to use. Even after that PR gets merged, the conda packages will need to be updated, etc. It's not clear to me how much effort this will take.

**Comment by kidzik** [comment]
@ViktorM you might try to modify this https://github.com/kidzik/conda-opensim/blob/master/opensim/bld.bat 
In theory, using the right branch in `git_rev` and changing the `python` version to `3.5` might already work. I will look into that as soon as we fix more critical issues before the running challenge.

**Comment by ViktorM** [comment]
Compiling will be the trickiest part for me, getting osim-rl work after it will be quite straightforward. Will test tomorrow.

**Comment by kidzik** [comment]
This build
https://anaconda.org/kidzik/opensim/4.0.0/download/linux-64/opensim-4.0.0-py36_15.tar.bz2
with this branch of osim-rl
https://github.com/stanfordnmbl/osim-rl/tree/python3
should already work with python3. There is only Linux version but as soon as we test it throughout I will compile Windows and Mac OS.
Also for the moment there is no guarantee that the two versions behave the same way (as they were build from different builds of OpenSim)

**Comment by ViktorM** [comment]
Thanks Lukasz! Will install and start testing on Linux tomorrow.

**Comment by ViktorM** [comment]
@kidzik met this error:

>>> import opensim
>>> from osim.env import RunEnv
>>> env = RunEnv(visualize=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/apexteam/vmakoviychuk/Deep_RL/osim-rl3/osim-rl/osim/env/run.py", line 34, in __init__
    super(RunEnv, self).__init__(visualize = False, noutput = self.noutput)
  File "/home/apexteam/vmakoviychuk/Deep_RL/osim-rl3/osim-rl/osim/env/osim.py", line 121, in __init__
    self.osim_model = Osim(self.model_path, self.visualize)
  File "/home/apexteam/vmakoviychuk/Deep_RL/osim-rl3/osim-rl/osim/env/osim.py", line 21, in __init__
    self.model = opensim.Model(model_path)
AttributeError: module 'opensim' has no attribute 'Model'

**Comment by kidzik** [comment]
Can you post the output of

    conda list

Thanks!

**Comment by ViktorM** [comment]
Hi Lukasz,

I flight out of the Moscow this weekend, will be able to check output only on Monday.

**Comment by ViktorM** [comment]
@kidzik:
```
(opensim-rl3) apexteam@apexubuntu:~/vmakoviychuk/Deep_RL/osim-rl3$ conda list
# packages in environment at /home/apexteam/anaconda3/envs/opensim-rl3:
#
opensim                   4.0.0                        15    file:///home/apexteam/vmakoviychuk/Deep_RL/osim-rl3

```

**Comment by kidzik** [comment]
Have you installed `osim-rl` (using python3 branch https://github.com/stanfordnmbl/osim-rl/tree/python3) and other packages?
I am getting
```
(osim-rl-py35) lukasz@lukasz-MOBILIZE-NMBL:~$ conda list
# packages in environment at /home/lukasz/anaconda2/envs/osim-rl-py35:
#
certifi                   2017.4.17                 <pip>
chardet                   3.0.4                     <pip>
freeglut                  2.8.1                         0  
gym                       0.9.2                     <pip>
idna                      2.5                       <pip>
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
numpy                     1.13.0                    <pip>
openblas                  0.2.19                        0  
opensim                   4.0.0                        15    local
openssl                   1.0.2l                        0  
osim-rl                   1.2                       <pip>
pip                       9.0.1                    py36_1  
pyglet                    1.2.4                     <pip>
python                    3.6.1                         2  
readline                  6.2                           2  
requests                  2.18.1                    <pip>
setuptools                27.2.0                   py36_0  
six                       1.10.0                    <pip>
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
urllib3                   1.21.1                    <pip>
wheel                     0.29.0                   py36_0  
xz                        5.2.2                         1  
zlib                      1.2.8                         3  
```
The way I create it is following
```
conda create -n osim-rl-py35
source activate osim-rl-py35
conda install https://anaconda.org/kidzik/opensim/4.0.0/download/linux-64/opensim-4.0.0-py36_15.tar.bz2
git clone https://github.com/stanfordnmbl/osim-rl.git
cd osim-rl
git checkout origin/python3
pip install .
python scripts/basic.py
```

**Comment by ViktorM** [comment]
Yes I've installed osim-rl python3 branch, you can see it in my log. Other packages have been already installed outside the env. And I was doing totally the same, the only difference I've installed opensim build not from git, but from download archive you previously posted. Will try now the variant you've posted 1-to-1.

Can you clarify a a Python version of osim-rl? You've created env with py35 name, but opensim build is py36. Was it just a mistype and I suppose python3 branch should work well with 3.6 too? Btw there is no need in additional support of Python 3.5+ now as new version of TF - 1.2 already has a support for Python 3.6 on Windows and for Linux it has been available for a while.

**Comment by kidzik** [comment]
The build is for python 3.6, indeed I mistyped in the comment and I've just fixed it. I've just checked everything again and it seems to work well on my Ubuntu 16.04. Thanks for testing!

**Comment by ViktorM** [comment]
I have totally the same error, I've seen with my installation:
```
(osim-rl-py36) apexteam@apexubuntu:~/vmakoviychuk/Deep_RL/osim-rl3/osim-rl$ python scripts/basic.py
Traceback (most recent call last):
  File "scripts/basic.py", line 1, in <module>
    from osim.env.run import RunEnv
  File "/home/apexteam/vmakoviychuk/Deep_RL/osim-rl3/osim-rl/osim/env/__init__.py", line 2, in <module>
    from .run import *
  File "/home/apexteam/vmakoviychuk/Deep_RL/osim-rl3/osim-rl/osim/env/run.py", line 1, in <module>
    import opensim
ModuleNotFoundError: No module named 'opensim'
```

**Comment by ViktorM** [comment]
And the same conda list output:
```
(osim-rl-py36) apexteam@apexubuntu:~/vmakoviychuk/Deep_RL/osim-rl3/osim-rl$ conda list
# packages in environment at /home/apexteam/anaconda3/envs/osim-rl-py36:
#
opensim                   4.0.0                        15    https://anaconda.org/kidzik/opensim/4.0.0/download
```

**Comment by kidzik** [comment]
Thank you @ViktorM , I will try on a clean installation. Can you tell me which distribution and version of linux you are using?

**Comment by ViktorM** [comment]
Ubuntu, version 16.04 if I remember correctly, I'm out access to this remote PC at the moment.

**Comment by ViktorM** [comment]
Yep, I remembered correctly:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:          16.04
Codename:     xenial
```

**Comment by marioyc** [comment]
Was this indicated somewhere in the challenge instructions? I just noticed after getting an error. Maybe adding "python=2.7" at the end of "conda create -n opensim-rl -c kidzik opensim git" would be a good idea.

**Comment by kidzik** [comment]
That's definitely a good idea, thanks @marioyc

**Comment by pavitrakumar78** [comment]
Hi,
Has anyone made opensim work on windows with python 3.5?

**Comment by nchentanez** [comment]
Would love to have Python 3.5+ support on Windows as well!

**Comment by pavitrakumar78** [comment]
@nchentanez Hey, the opensim repo has instructions on how to install it on windows [here.](https://github.com/opensim-org/opensim-core#for-the-impatient-windows). If you have any errors, [this](https://github.com/opensim-org/opensim-core/issues/1839) discussion may help.

**Comment by ViktorM** [comment]
@pavitrakumar78 this instruction includes python 2: choco install python2 jdk8 swig - which is not very helpful. Also the request was to have similar quite simple installation of the whole environment for the challenge with Python 3.5+ as it is for Python 2.7

**Comment by ViktorM** [comment]
Either on Windows or on Linux installation instructions are only for 2.7 and are very simple:
`conda create -n opensim-rl -c kidzik opensim git python=2.7`
But to get it working with the Python 3 it requires to spend a lot of additional time just to start.

**Comment by pavitrakumar78** [comment]
@ViktorM All you have to do is execute the instructions in the 2nd link I provided. Just copy, paste in PowerShell. It also takes care of dependencies. I do not use conda env, so the instructions provided in the links in my comment are related to general python and not IDE-specific. I doubt you are going to get anything simpler than what is mentioned in opensim's repo instructions for py3.5+windows.

**Comment by ViktorM** [comment]
Thanks @pavitrakumar78. 

Quick update - for Linux Python 3.6 installation works excellent if instead of python=2.7 to use command
`conda create -n opensim-rl -c kidzik opensim git python=3.6`
I think docs should be updated. In pdf on the crawdai no python version requirement is mentioned at all. On the github in ReadMe only 2.7 is mentioned. I think there can be explicitly written now that either 2.7 or 3.6 installation are supported and written an instructions for both of them.

**Comment by VsonicV** [comment]
@kidzik Hi, I try to install from the python 3 branch you posted (https://github.com/stanfordnmbl/osim-rl/tree/python3), but this branch seems to be removed, could you please suggest which branch should I use for python 3.6 support?

**Comment by kidzik** [comment]
Hi @VsonicV , the Python 3.6 version of osim-rl is now on the `master` branch so you can just install it directly with

    pip install git+https://github.com/stanfordnmbl/osim-rl.git

if Python 3 is your default python enivronment.

**Comment by VsonicV** [comment]
@ViktorM Hi, I have tried the command 
`conda create -n opensim-rl -c kidzik opensim git python=3.6`
but got the error:
`UnsatisfiableError: The following specifications were found to be in conflict:
  - opensim -> python 2.7* -> openssl 1.0.1*
  - python 3.6*`
May I know how you solved this issue?

**Comment by kidzik** [comment]
Note that right now the Python 3.6 version of the conda build is only available for Linux. If you have Windows you need to compile OpenSim from source https://github.com/opensim-org/opensim-core

**Comment by VsonicV** [comment]
@kidzik I was using Python 3.6 in mac OSX, and incurred the following error when `import opensim`:
ImportError: dlopen(/Users/xin.qiu/anaconda/lib/python3.6/site-packages/opensim/_simbody.so, 2): no suitable image found.  Did find:
	/Users/xin.qiu/anaconda/lib/python3.6/site-packages/opensim/_simbody.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
Just for your reference, thanks

**Comment by kidzik** [comment]
Hi @VsonicV, unfortunately, there is only a Python 3.6 build for Linux right now. On OSX you need to either use 2.7 or install it from source https://github.com/opensim-org/opensim-core
A quick solution for using 3.6 on a mack could be a docker container.

**Comment by kidzik** [comment]
The conda package with python 3.6 is now the official version on each platform with binaries available for each platform.
