### ISSUE TITLE
something about submit and reset

### ISSUE THREAD

**Issue by Ailsa1994** [stanfordnmbl/osim-rl#161]
There is something confused me about the example of sbmit.py. 

`
while True:

    print(observation)

    [observation, reward, done, info] = client.env_step(env.action_space.sample().tolist())

    if done:

        observation = client.env_reset()

        if not observation:

            break`
why should be env_reset when the condition is done? should‘t it be 

`
while True:

    print(observation)

    [observation, reward, done, info] = client.env_step(env.action_space.sample().tolist())

    if done:

            break`

if then, the video of submition will only be once

**Comment by kidzik** [comment]
The semantics are the following:
* run steps of the trail
* if done, restart
* if restart doesn't give an observation -- terminate

That's true that it's not the most intuitive, but for our very basic workflow, it seems to work ok.

The submission script does not assume the number of trials -- it just follows what the server is sending.
