### ISSUE TITLE
Making sense of experimental data 

### ISSUE THREAD

**Issue by sandipan1** [stanfordnmbl/osim-rl#162]
I am not to understand how to use the experimental data given in docs .In the hamner2013muscle dataset there are data given for 20 subjects .Each folder containing 
![image](https://user-images.githubusercontent.com/14030793/44191750-427de980-a14a-11e8-8b80-20fbbbee371e.png)

I am not sure about where are muscle activation from the experiments
Is it the CMC results ? if so there are negetive values , positive values (>1) . How do I use that for simulating muscle activation (for the competition)?

**Comment by kidzik** [comment]
Raw EMG recordings are here https://simtk.org/frs/?group_id=603 (note however that there is no EMG for all muscles and these are noisy signals in general).
CMC is an approximation of muscles activity given the model (probably more useful than raw signals in this case). Note that in the output you have results from many stages of optimization (so the early files have values which don't match conditions). To my understanding, negative values are also a consequence of the fact that the optimization algorithm did not find a result matching all conditions.
For RL it might be enough to just assume that these are zeros and start to search around these 'incorrect' trajectories.

**Comment by sandipan1** [comment]
@kidzik @carmichaelong 
I listed the muscles in control.sto and tried to match it with ProstheticsEnv observation muscles.
I couldn't find muscle "abd_r"  ,"abd_l"  "hamstrings_r"  , "hamstrings_l"   in controls.sto
There are  "add_long_r"	"add_brev_r"	"add_mag1_r"	"add_mag2_r"	"add_mag3_r"   along with their left leg counterparts in controls.sto .However there is only "add_r" in the muscle set. How do I choose?
Similarly 
glut_max1_r	glut_max2_r	glut_max3_r   in control.sto    but only "glut_max_r" in muscle set
vas_med_r	vas_int_r 	vas_lat_r        in controls.sto  but  only  "vasti_r" in muscle set
med_gas_l	lat_gas_l                               in controls.sto   but  only  ""gastroc_l" in muscle_set

How do I map these muscles?

**Comment by kidzik** [comment]
The CMC output wouldn't produce the movement anyway, so you can treat it as some approximation and use it as a reasonable starting point for the reinforcement learning (i.e. trying to first build a network in a supervised manner).
You can also try to rerun CMC with the model from the challenge.

**Comment by sandipan1** [comment]
Okay.Thanks

**Comment by ThGravo** [comment]
@sandipan1 Did you manage to rerun the CMC?

**Comment by sandipan1** [comment]
Nope .I tried to change the setup files and run but the execution got stuck while running CMC tool.
