### ISSUE TITLE
Installation Issues - No module named 'osim'

### ISSUE THREAD

**Issue by nicos1993** [stanfordnmbl/osim-rl#170]
Hi all, 

I am currently experiencing some difficulties with the 'installation' I believe. Myself and another colleague have both followed the installation guidelines on our own laptops (both Windows 10), he seems to be able to get the introductory code to run as expected:
```python
from osim.env import ProstheticsEnv

env = ProstheticsEnv(visualize=True)
observation = env.reset()
for i in range(200):
    observation, reward, done, info = env.step(env.action_space.sample())_
```
I on the other hand receive the following error message:
```python
_ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-552dc0e04ec1> in <module>()
----> 1 from osim.env import ProstheticsEnv
      2 
      3 env = ProstheticsEnv(visualize=True)
      4 observation = env.reset()
      5 for i in range(200):

ModuleNotFoundError: No module named 'osim'_
```
Does anyone have any suggestions for overcoming this problem?

Thanks

Nicos Haralabidis

**Comment by Poddiachyi** [comment]
> Note that `source activate opensim-rl` activates the anaconda virtual environment. You need to type it every time you open a new terminal.

Maybe this will help. You need to activate virtual environment at first.

**Comment by Poddiachyi** [comment]
Had the same issue. I deleted conda environment and installed everything again. Worked for me.

Don't forget that you need to activate the environment at first.
`source activate opensim-rl`
And only then start working.
