### ISSUE TITLE
Submission result differs from local 

### ISSUE THREAD

**Issue by whikwon** [stanfordnmbl/osim-rl#174]
I ran the evaluation code and could get 1999 reward. but when i submit the result, total reward becomes half value. Why this happens?

![image](https://user-images.githubusercontent.com/30768596/46510307-26154800-c883-11e8-83fc-924c6b6dcf37.png)

**Comment by kidzik** [comment]
Please follow these instructions
https://github.com/stanfordnmbl/osim-rl#submission
basically, you need to restart the environment and send the next set of actions for the second episode.

While in the first round the result might be the same, in the second the random seeds are different and the results from the runs will vary.

**Comment by whikwon** [comment]
Thanks
