### ISSUE TITLE
GPU computation

### ISSUE THREAD

**Issue by Poddiachyi** [stanfordnmbl/osim-rl#175]
Hello.

Is there a way to do environment computation on a GPU? As far as I understand there is no problem with training an agent but the environment is a bottle neck. 

Sorry if there was such question before, I couldn't find it.

**Comment by kidzik** [comment]
No, unfortunately, due to complex model dynamics these operations are not easy to parallelize on a GPU at the moment. Typical approach that participants take is to run simulations on multiple CPUs and the network training on GPUs.
