### ISSUE TITLE
【bug】Random seeds are not properly set up in round2 evaluation

### ISSUE THREAD

**Issue by yobobobo** [stanfordnmbl/osim-rl#179]
https://github.com/stanfordnmbl/osim-rl/blob/3ceadccc2f9104c9012281a482cfff5203f703bd/osim/env/osim.py#L515
https://github.com/stanfordnmbl/osim-rl/blob/3ceadccc2f9104c9012281a482cfff5203f703bd/osim/env/osim.py#L508

Target velocity and heading were generated here and they are done by using _random_ and _numpy_ libraries.
To make the random seed work as expected, which means we would have same target velocity and heading given the same seed, it should be 
```python
np.random.seed(seed)
random.seed(seed)
```
But the random seed was set only in here 
https://github.com/stanfordnmbl/osim-rl/blob/3ceadccc2f9104c9012281a482cfff5203f703bd/osim/env/osim.py#L432

**Comment by mattiasljungstrom** [comment]
Yes, in my test code I've been doing the following to get deterministic tests:

np.random.seed(seed)
random.seed(seed)
obs = env_test.reset(project=False)
...

**Comment by kidzik** [comment]
Fixed with https://github.com/stanfordnmbl/osim-rl/commit/48f469fb55d8a1a84b500d332b1ba236f27817c8
