### ISSUE TITLE
INIT_POSE, state.getQ()

### ISSUE THREAD

**Issue by bmmi** [stanfordnmbl/osim-rl#183]
Could you explain what each item means in [`QQ = state.getQ()`](https://github.com/stanfordnmbl/osim-rl/blob/b43f728f283bb11364d934356893595bfe97eebb/osim/env/osim.py#L456) for the model `gait14dof22musc_20170320.osim` and how they are related to the 14 DoFs? e.g. What are the missing `8, 11, 12` -th elements in `QQ`? I think this is related to [pelvis state](https://github.com/stanfordnmbl/osim-rl/blob/b43f728f283bb11364d934356893595bfe97eebb/osim/env/osim.py#L540).

**Comment by smsong** [comment]
QQ[8], QQ[11], QQ[12] are all currently locked for the competition environment. They are:
QQ[8]: right hip rotation (yaw)
QQ[11]: left hip rotation (yaw)
QQ[12]: lumbar extension
