### ISSUE TITLE
L2M2019Env observation_space.high is all zero

### ISSUE THREAD

**Issue by joneswong** [stanfordnmbl/osim-rl#184]
Could you fix the observation_space.low and .high to be consistent with the actual value ranges? Currently, the observation_space.low and .high are all zeros. It would be helpful to respect gym interface. Thanks

**Comment by smsong** [comment]
L2M2019Env now defines its observation_space. https://github.com/stanfordnmbl/osim-rl/commit/43ac8db3d89b4c14d4a9592ae49a75ef16c88849
