### ISSUE TITLE
What is the officially permitted way to get the observation

### ISSUE THREAD

**Issue by yobobobo** [stanfordnmbl/osim-rl#187]
https://github.com/stanfordnmbl/osim-rl/blob/43ac8db3d89b4c14d4a9592ae49a75ef16c88849/osim/env/osim.py#L550

Now the competitors are allowed to get three kinds of observation:
- Project=False: get original observation without any feature preprocessing.
- Project=True& obs_as_dict=True: get a dict of the observation with some feature preprocessing.
- Project=False& obs_as_dict=False: get a vector representing the observation with some feature preprocessing.

We want to sure that which way is allowed in submission? or all of these ways are permitted in submission?

**Comment by smsong** [comment]
@yobobobo The evaluation environment is set as `model='3D'`, `difficulty=2`, `project=True`, and `obs_as_dict=True` Thank you for the question. We will clarify this on the competition page.

**Comment by drozzy** [comment]
Is there some (standard) way of taking a dict produced and converting it to an array? I want to train with `obs_as_dict=False`, but your evaluator supplies dict.

Also, what is the purpose of `project` option and how is it different from `obs_as_dict`? I can't seem to find an explanation.

**Comment by smsong** [comment]
@drozzy 
- Setting `project=True` and `obs_as_dict=False` will give you an array.
- Or you can refer to get_observation (https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/osim.py#L659) to convert obs_dict into an array.
- With `project=False` you will get a dict that consists of more information. You can use it as you want for training but won't have access to it during evaluation.

**Comment by yobobobo** [comment]
@smsong 
Does that means we can have three kinds of observation by changing arguments passing to the evaluator ?

**Comment by yobobobo** [comment]
Got it! Thanks for replying.

**Comment by drozzy** [comment]
Sorry, I'm still having trouble understanding. If I write my own observation wrapper using         https://github.com/stanfordnmbl/osim-rl/blob/ffd1a98852da3d6ce82304908c4a985539bd66f9/osim/env/osim.py#L659 then my `observation_space` shape `Box(339,)` seems to no longer be correct...

Just curious why the default observation is not just a numpy array?

**Comment by smsong** [comment]
@drozzy 
As the observation space is large, we thought a dictionary with description keys would be easier for those who want to know what the values mean. And we thought to convert the dictionary to an array would be straightforward.

Sorry that the `observation_space` doesn't seem to be correct to you.
`observation_space` is defined/explained
https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/osim.py#L419-L444
and is supposed to define the space for the observation array you get when `obs_as_dict=True`.

Does your observation wrapper produce the same array from what you get when you set `obs_as_dict=True`?

**Comment by drozzy** [comment]
Found the issue, here it is in a new issue: https://github.com/stanfordnmbl/osim-rl/issues/192
