### ISSUE TITLE
Why the project = True obs_as_dict = True gives an array with different size (339 locally, 710 on crowdai evaluation)?

### ISSUE THREAD

**Issue by yhamidullah** [stanfordnmbl/osim-rl#193]
Hi,
I tried 
1) **project = True obs_as_dict = True** locally : gives me after flattening an array of  shape (339,)
2) **project = False obs_as_dict = False** locally : gives me after flattening and array of shape (710,)

But sending to evaluation at crowdai, knowing that it is setted **project = True obs_as_dict = True**, I expect to get the same shape (339,), but got (710,)

So I guess that in at crowdai it is setted **project = False obs_as_dict = False**
I trained my model with an input of the observation space so I can't do anything to reformat these 710 values to 339 to have the expected observation.

Is there a workaround?

Thanks

**Comment by spMohanty** [comment]
@yhamidullah : The evaluator uses [this release](https://github.com/stanfordnmbl/osim-rl/releases/tag/v3.0.3) , can you confirm if you face the issue even with this release ?

@kidzik : Should we make a new release with any new changes ? just a minor patch should do, as long as the release is also available on PyPI.

**Comment by yhamidullah** [comment]
![image](https://user-images.githubusercontent.com/13780954/62057611-42beaa00-b220-11e9-9432-b759fd6422f8.png)

Yes I confirm that I use the release 3.0.3

**Comment by spMohanty** [comment]
@yhamidullah : Can you try making a submission again ?

**Comment by yhamidullah** [comment]
@spMohanty  Another submission is sent, and it's in evaluation queue actually, since 26 minutes.

**Comment by spMohanty** [comment]
@yhamidullah : This seems to be working fine now : https://gitlab.aicrowd.com/yhamidullah/neurips2019-learn-to-move/issues/12

**Comment by yhamidullah** [comment]
Thanks very much!

**Comment by hanszeng** [comment]
Hi, @spMohanty I follow the tutorial: https://github.com/stanfordnmbl/neurips2019-learning-to-move-starter-kit and find that the local grader still return 710 dim observation in the local debug mode.
