### ISSUE TITLE
Is it necessary to add absolute  to the speed difference in each frame?

### ISSUE THREAD

**Issue by hanszeng** [stanfordnmbl/osim-rl#195]
Is it more reasonable to add absolute after the` (v_body - v_tgt)`
https://github.com/stanfordnmbl/osim-rl/blob/dfd5e76415345293df8981d258d8ad6d5d472c7f/osim/env/osim.py#L767

**Comment by smsong** [comment]
@hanszeng Thanks for the question.
The `(v_body - v_tgt)` term allows `v_body` to deviate from `v_tgt` within a step as real humans do in normal walking.
`reward_footstep_v` is calculated as
https://github.com/stanfordnmbl/osim-rl/blob/dfd5e76415345293df8981d258d8ad6d5d472c7f/osim/env/osim.py#L779
to penalize the deviation of the mean velocity during a step from `v_tgt`.

**Comment by zenghsh3** [comment]
Got it. Thanks for the explanation.

**Comment by hanszeng** [comment]
It's clear. Thank you for your explanation.
