### ISSUE TITLE
The last footstep reward should add reward_footstep_v and reward_footstep_e

### ISSUE THREAD

**Issue by hanszeng** [stanfordnmbl/osim-rl#196]
I can get a full credit 300 when my first footstep doesn't finish in 1000 frames.

https://github.com/stanfordnmbl/osim-rl/blob/560cfd37c4bd3164830dd80f29418a11f34caf51/osim/env/osim.py#L797

**Comment by smsong** [comment]
@hanszeng Thank you very much for finding out this critical bug. It is now fixed: https://github.com/stanfordnmbl/osim-rl/commit/55db058307cb60ffdc9852350f912e4bb317c411

**Comment by hanszeng** [comment]
Looks good~
