### ISSUE TITLE
Duplicated DDPG agent scripts

### ISSUE THREAD

**Issue by ViktorM** [stanfordnmbl/osim-rl#2]
Hi Lukasz,

Currently there are 2 DDPG training scripts, in osim-rl/osim/sandbox/train.ddpg.py and osim-rl/scripts/keras-rl/train.ddpg.py

Is this intended? The osim-rl/scripts/keras-rl/train.ddpg.py is newer but it doesn't contain option to chose standing environment. And human env also isn't imported.

**Comment by kidzik** [comment]
Hi, sandbox is obsolete please use the file from scripts. I've just added other environments 7fdab2f54da33e3864d5db7fd8d2b85d2d6bafad
