### ISSUE TITLE
Round2 call get_reward function twice, which will make reward calculation wrong.

### ISSUE THREAD

**Issue by hanszeng** [stanfordnmbl/osim-rl#208]
The following two line will call get_reward function both. @smsong 

https://github.com/stanfordnmbl/osim-rl/blob/e77a4345df0e1bca8527062a326ad386c0e013c6/osim/env/osim.py#L556

https://github.com/stanfordnmbl/osim-rl/blob/e77a4345df0e1bca8527062a326ad386c0e013c6/osim/env/osim.py#L572

**Comment by smsong** [comment]
Thanks a lot! That is now fixed: https://github.com/stanfordnmbl/osim-rl/commit/27c3e9cb17cdb6aff508e5ad192a813188a542e3
