### ISSUE TITLE
setting seed not working

### ISSUE THREAD

**Issue by Geogre19** [stanfordnmbl/osim-rl#209]
I tried running the following test code twice, but the prints were different. Are they supposed to be identical given the same seed 0?

https://github.com/stanfordnmbl/osim-rl/blob/master/envs/target/test_v_tgt.py

--------------------------output----------------------
`python3 test_v_tgt.py `
```shell
>> Target achieved at 8.61 sec
>> Target achieved at 15.13 sec
```

`python3 test_v_tgt.py `
```shell
>> Target achieved at 6.92 sec
>> Target achieved at 15.63 sec
```

**Comment by smsong** [comment]
Try with an integer larger than 0 as a seed.

**Comment by Geogre19** [comment]
It work! Thanks for replying.
