### ISSUE TITLE
"AttributeError: can't set attribute" in "Basic Usage" step

### ISSUE THREAD

**Issue by arnaghosh** [stanfordnmbl/osim-rl#21]
Hi,
Thanks for the detailed installation steps. I tried installing and running the environment on Windows 10 with Python 2.7. The installation was pretty smooth and I also got through with the "import opensim" step without errors. However, when I write the 2nd line of Basic Usage - "env = RunEnv(visualize=True)" , I get the Attribute Error. The entire error log is:-
Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file C:\Users\arna\Anaconda2\envs\opensim-rl\lib\site-packages\osim\env\../models/gait9dof18musc.osim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\arna\Anaconda2\envs\opensim-rl\lib\site-packages\osim\env\run.py", line 29, in __init__
    super(RunEnv, self).__init__(visualize = False, noutput = self.noutput)
  File "C:\Users\arna\Anaconda2\envs\opensim-rl\lib\site-packages\osim\env\osim.py", line 137, in __init__
    self.spec = Spec()
AttributeError: can't set attribute

Thanks for the help.

**Comment by kidzik** [comment]
Can you please try to update the osim environment with 

    pip install git+https://github.com/stanfordnmbl/osim-rl.git -U 

I have just added the `spec=None` to the class definition in the last commit b7ffdf110eb24713b76fa0a23fe0bb9de4112e74 and it should have got fixed. Thanks!

**Comment by arnaghosh** [comment]
Hi,
Thanks for the quick reply. I just tried doing it and it works perfectly fine.
Thank you.

**Comment by kidzik** [comment]
There was another small issue related to tha same update, please uptade the environment 

pip install git+https://github.com/stanfordnmbl/osim-rl.git -U 

Thanks and sorry about that :)
