### ISSUE TITLE
No Module names ProstheticsEnv

### ISSUE THREAD

**Issue by mcmips** [stanfordnmbl/osim-rl#223]
I followed the instructions to install osim-rl on my windows machine.
I can get osim-rl and import osim and osim.env is also present

BUT, I can not locate ProstheticsEnv

>>> dir(osim.env)
['Arm2DEnv', 'Arm2DVecEnv', 'L2M2019Env', 'OsimEnv', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'arm', 'convert_to_gym', 'gym', 'math', 'np', 'opensim', 'os', 'osim', 'random', 'utils']

>>> from osim.env import ProstheticsEnv
Traceback (most recent call last):

File "<ipython-input-9-e9a8a6e76a0a>", line 1, in <module>
from osim.env import ProstheticsEnv

ImportError: cannot import name 'ProstheticsEnv'

Please help..

**Comment by mcmips** [comment]
With Branch Ver2.1 it is working that is i am able to import ProstheticsEnv. Please Confirm..

**Comment by kidzik** [comment]
Perfect, thanks for finding this. Yes, ProsteticsEnv has been removed after the NeurIPS 2018 challenge to reduce maintenance load. It shouldn't be too much work to make it compatible with the current master though.
