### ISSUE TITLE
Are there residual and/or reserve actuators in the model?

### ISSUE THREAD

**Issue by q138ben** [stanfordnmbl/osim-rl#230]
Generally residual and reserve actuators are added in a musculoskeletal model to control the global position and orientation of a model and make up for insufficient muscle strength during a simulation respectively. But I cannot, to the best of my observation, find any of these actuators in the model or controller. 

Are there residual and/or reserve actuators in the model? If yes, can you point out where they locate? If no, how do you ensure muscles strong enough to perform certain movement?

**Comment by smsong** [comment]
No, there is no residual/reserve actuators in the model (as in other physics simulation). So there is no guarantee that the model can perform the motions you want (as for real humans). However, as the musculoskeletal model includes the major leg muscles with typical strengths, it likely would perform typical locomotion behaviors.

**Comment by q138ben** [comment]
Thanks.
