### ISSUE TITLE
Visualizer shows up as blank

### ISSUE THREAD

**Issue by Royii61** [stanfordnmbl/osim-rl#238]
Hi，
I'm new to opensim, I just installed the environment. 
But when I run
from osim.env import Arm2DEnv
env = Arm2DEnv(visualize = True)

the visualizer shows blank
<img width="602" alt="c38ac320573e714c961f67ab0398a47" src="https://user-images.githubusercontent.com/95224196/144746218-c1405446-3cb4-45f6-a58e-d85d0b830f3e.png">

from osim.env import Arm2DEnv
env = Arm2DEnv(visualize = True)
Updating Model file from 20303 to latest format...
Loaded model arm26 from file C:\Users\lenovo\anaconda3\envs\opensim-rl\lib\site-packages\osim\env\../models/arm2dof6musc.osim

simbody-visualizer: received Shutdown message. Goodbye.

simbody-visualizer: received Shutdown message. Goodbye.

**Comment by SoroushK93** [comment]
Hi,
I have the same problem. Would you please let me know how did you solve it?
Thanks,
