### ISSUE TITLE
Error with execution of the 200 iterations of the simulation

### ISSUE THREAD

**Issue by ViktorM** [stanfordnmbl/osim-rl#27]
Hi,

Tried default installation of the python 2.7 version of opensim-rl and hit an error when started script from the Basic usage chapter - execution of the 200 iterations. During installation I exactly followed instructions except of the name of conda enviroment. You can find a log below:
```
(opensim-rl27) apexteam@apexubuntu:~/vmakoviychuk/Deep_RL/osim-rl27$ python -c "import opensim"
(opensim-rl27) apexteam@apexubuntu:~/vmakoviychuk/Deep_RL/osim-rl27$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from osim.env import RunEnv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named osim.env
>>> import opensim
>>> from osim.env import RunEnv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named osim.env
```

**Comment by kariefury** [comment]
osim.env is a file provided by this git repo. If you have a cloned copy of the repo, then from the root directory it will find the module osim.env.

**Comment by ViktorM** [comment]
@kariefury yes I know. And I have of course cloned copy - I followed the instructions and in addition checked it's presence after I finished all the steps. And I made a few clean attempts deleting old conda environment and the whole cloned directories. Anyway this Linux PC has died and I can't try it again before the new one will arrive. So I'll close this issue.
