### ISSUE TITLE
[Hacked] osim-rl now runs on Win7 x64 + py35

### ISSUE THREAD

**Issue by ctmakro** [stanfordnmbl/osim-rl#29]
I wrote a detailed description here:
<https://github.com/ctmakro/stanford-osrl/blob/master/README.md#note-for-users-on-win7-x64--python-35-2017-07-06>
hope that helps!

**Comment by kidzik** [comment]
That's great, thank you very much! I will test it soon and integrate with what we have

**Comment by kidzik** [comment]
Thread now linked in the FAQ in readme. Closing the issue.
