### ISSUE TITLE
ImportError: No module named gym

### ISSUE THREAD

**Issue by kariefury** [stanfordnmbl/osim-rl#32]
If you do not have OpenAI Gym installed, it needs to be install to run the suggested 'first try' code.

`pip install gym`

**Comment by kidzik** [comment]
Have you installed the environment using `pip`? If so, it should also install the gym (https://github.com/stanfordnmbl/osim-rl/blob/master/setup.py#L22) and there is some bug.
If not, then everything is ok and I will just state it somewhere in the tutorial.

**Comment by kariefury** [comment]
I skipped a line in the tutorial since I had already cloned the git repo, my mistake:

`pip install git+https://github.com/stanfordnmbl/osim‐rl.git'

Thank you!
