### ISSUE TITLE
Introducing energy penalty to the reward

### ISSUE THREAD

**Issue by ViktorM** [stanfordnmbl/osim-rl#34]
Hi,

I've noticed in the previous contest - Learning to walk and in the current one most of the solutions were jumping ones. But humans usually don't use jumps for locomotion. I'm sure that experts in biomechanics can tell a lot why jumps aren't good for walking and running, I suspect one of the reasons is that jumping with the same speed spends much more energy than walking.  So may be it makes sense to introduce new small biologically inspired penalty term to the reward in such way that jumping still can be a viable solution, but walking/running the same distance will receive larger reward.

**Comment by kidzik** [comment]
Energy constraint makes sense for long distances, but for a 5-10 seconds run it's normally not the priority, so we deliberately didn't add it. However, we added a penalty for the use of ligaments (which humans control to avoid injuries). 
Of course jumping is not the most efficient pattern, but not only in terms of the energy but also just in terms of velocity. So as long as the simulation is correct, regular 'human run' should be faster, also without energy constraints.
The reason why we get jumping as the best result is probably that it is a local minimum much easier to reach than a complex human running pattern.

**Comment by kidzik** [comment]
It is a good point though, I will add an explanation to the tutorial.

**Comment by ctmakro** [comment]
The simulation setup prohibits rotation around x and y axis, which possibly made jumping easier than running.
