### ISSUE TITLE
Pickling OsimEnv

### ISSUE THREAD

**Issue by hieunm131** [stanfordnmbl/osim-rl#36]
Some libraries which are capable of parallel processing get the following error when trying to pickle the OsimEnv:  `TypeError: can't pickle SwigPyObject objects`. 

I check the code and see that the cause:
```
state['pelvis']  <class 'opensim.simulation.PlanarJoint'>
<opensim.simulation.PlanarJoint; proxy of <Swig Object of type 'OpenSim::PlanarJoint *' at 0x7fefa7e07ae0> > 
```

What should I do to make `state['pelvis']` pickleable, or convert it to other valid data types?

**Comment by kidzik** [comment]
Do you really need to pickle the entire environment? For most of the use cases, It should be enough to just pickle the parameters of the simulations (and your model etc.). Can you tell a little bit more on the actual use case?

**Comment by hieunm131** [comment]
Thanks for the reply. I found a way to avoid pickling the env, so I close this.

**Comment by GolovanovSrg** [comment]
state['pelvis'] store some information?
