### ISSUE TITLE
Is the timestep_limit 1000 in version 1.3?

### ISSUE THREAD

**Issue by LiberiFatali** [stanfordnmbl/osim-rl#39]
This should be changed from 500 to 1000

https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/osim.py#L67-L76

```
class Spec(object):
    def __init__(self, *args, **kwargs):
        self.id = 0
        self.timestep_limit = 500

class OsimEnv(gym.Env):
    stepsize = 0.01
    integration_accuracy = 1e-3
    timestep_limit = 1000
    test = False
```

**Comment by kidzik** [comment]
Fixed. The environment actually reads it from itself, but spec is there for compatibility with `gym`.
Thanks!
