### ISSUE TITLE
Ligaments penalty is divided by 10000, not 1000

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [stanfordnmbl/osim-rl#42]
From README:

> The penalty in the total reward is equal to the sum of forces generated by ligaments over the trial, divided by 1000.

https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/run.py#L76:

        return delta_x - math.sqrt(lig_pen) * 0.0001

**Comment by kidzik** [comment]
Thanks!
