### ISSUE TITLE
Simulation speed slower than real time

### ISSUE THREAD

**Issue by danijar** [stanfordnmbl/osim-rl#46]
Hi, thanks for hosting this challenge! For us the simulation (without visualization) runs at about 30 steps per second of real time. With the control frequency of 0.01 seconds, this means the simulation runs 3.33 times slower than real time. This seems quite slow. Is this performance expected or is there something wrong with our setup?

**Comment by kidzik** [comment]
Yes, the simulator can be slower than real time (depends on the complexity of the integration of a given step). In OpenSim precision of the computation is of higher priority.
   
This is a part of the challenge -- there are good algorithms for dealing with computationally simple problems, yet the interesting question is if current RL techniques generalize to more difficult environmnets.

**Comment by danijar** [comment]
Thanks for your response!
