### ISSUE TITLE
Failed to start the visualizer inside the virtual environment 

### ISSUE THREAD

**Issue by holdonyb** [stanfordnmbl/osim-rl#47]
When I start the visualizer in the conda virtual environment, I got this:

Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file /home/username/anaconda2/envs/opensim-rl/lib/python2.7/site-packages/osim_rl-1.4.1-py2.7.egg/osim/env/../models/gait9dof18musc.osim
freeglut (simbody-visualizer): OpenGL GLX extension not supported by display ':0.0'

And it was stuck like forever. 

The system is Ubuntu 14.04 
with CUDA 8.0

**Comment by spMohanty** [comment]
@holdonyb : If you are trying to run this on a server, then either you will need to do X11 forwarding, or you will need to have a fake display using xvfb.
The error suggests that opengl cannot find a DISPLAY to render the visualisation on.

Depending on what environment your ssh-client is running on, you should be able to do X11 forwarding by logging into the server by : 
```
ssh -X username@serveraddress
```

If you are trying to login from MacOSx onto the server, then, you will also have to install XQuartz on your laptop by following the instructions here : https://www.cyberciti.biz/faq/apple-osx-mountain-lion-mavericks-install-xquartz-server/
