### ISSUE TITLE
Cannot find ami-971be8ee

### ISSUE THREAD

**Issue by ShangtongZhang** [stanfordnmbl/osim-rl#50]
Is it only me or ami-971be8ee is missing? I cannot find it in AWS.
![image](https://user-images.githubusercontent.com/6715118/29279969-c338d8fe-80d6-11e7-88fc-2a2700f42d3c.png)

**Comment by kidzik** [comment]
It seems it's only available in the region in which I created it, in Ireland. I've just copied it to N. Virginia and Singapore (it should appear soon). Which region are you using?

**Comment by ShangtongZhang** [comment]
Oh cool! I found it after I switched to Ireland. I'm in Canada and my default region is Ohio.

**Comment by kidzik** [comment]
Great, I copied it to Ohio as well.

**Comment by ShangtongZhang** [comment]
Thanks a lot for your help!
