### ISSUE TITLE
Cannot find opensim machine on AWS

### ISSUE THREAD

**Issue by DoraXingyu** [stanfordnmbl/osim-rl#51]
Search of machine ami-971be8ee returns empty

**Comment by kidzik** [comment]
Hi, which region are you using?

**Comment by DoraXingyu** [comment]
My account region is U.S, if that is what you mean.

**Comment by kidzik** [comment]
I mean the region you are using in AWS. It's in the right-top corner as you can see here
https://camo.githubusercontent.com/7b98428cabccb5b1d67240bdcb72e35c734edee6/68747470733a2f2f73332d65752d776573742d312e616d617a6f6e6177732e636f6d2f6b69647a696e736b692f6f70656e73696d2d616d692f312e706e67
Right now the AMI in US should be available in North Virginia and Ohio. I can copy it to the region you are using as well.

**Comment by DoraXingyu** [comment]
Found the AMI in Ireland. But they are not available in North Virginia or Ohio.

**Comment by kidzik** [comment]
Indeed permissions in NV and Ohio were wrong. Can you check now?

**Comment by DoraXingyu** [comment]
I can see them in NV and Ohio now.
