### ISSUE TITLE
In the first observation state is computed before the reset

### ISSUE THREAD

**Issue by kidzik** [stanfordnmbl/osim-rl#53]
As mentioned here https://github.com/stanfordnmbl/osim-rl/issues/52 we have an issue with
https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/run.py#L60-L62
It should only affect the first observation.

**Comment by syllogismos** [comment]
This fix should also give the same first observation for the same seed right?

**Comment by kidzik** [comment]
That's right, the first observation after each reset.

**Comment by ctmakro** [comment]
i wrote some code to count the number of obstacles based on the sum of `relative x distance of ball to pelvis` and `current pelvis x position`. Sometimes I count more than 3 obstacles. The code that generates the obstacles is too convoluted. This issue may reveal the underlying cause.

**Comment by ctmakro** [comment]
This is confirmed.

```python
from osim.env.run import RunEnv
env = RunEnv(visualize=False)

observation = env.reset(difficulty = 2)

ball_log = []

pelvis_x = observation[1]
ball_relative = observation[38]
ball_absolute = pelvis_x + ball_relative

ball_log.append(ball_absolute)

for i in range(200):
    observation, reward, done, info = env.step(env.action_space.sample())

    pelvis_x = observation[1]
    ball_relative = observation[38]
    ball_absolute = pelvis_x + ball_relative

    ball_log.append(ball_absolute)

    if done:
        env.reset()
        break

print(ball_log)
```
the result says

```text
[100.0, 1.5812903531956022, 1.5812903531956022, 1.5812903531956022, 1.5812903531956022 ...
```
the absolute position of the obstacle(ball) is incorrect on first observation.

**Comment by kidzik** [comment]
Fixed in https://github.com/stanfordnmbl/osim-rl/tree/ver1.5
