### ISSUE TITLE
Reset with seed==0 fails

### ISSUE THREAD

**Issue by kidzik** [stanfordnmbl/osim-rl#54]
As mentioned in https://github.com/stanfordnmbl/osim-rl/issues/52. It happens due to a buggy condition
https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/run.py#L229-L230

**Comment by ctmakro** [comment]
```py
if seed is None:
```

**Comment by ctmakro** [comment]
#55

**Comment by kidzik** [comment]
We are using positive seeds in the grader, so it shouldn't make difference for the challenge. Yet, of course, checking if it's None makes more sense, as you suggested.
