### ISSUE TITLE
Grader does not force the restart

### ISSUE THREAD

**Issue by kidzik** [stanfordnmbl/osim-rl#56]
It seems it's possible to send actions even in the finished environment if users ignore the `done` flag
https://github.com/kidzik/osim-rl-grader/blob/master/gym_http_server.py#L150-L167

**Comment by ctmakro** [comment]
Apparently you didn't wrote the core logic in a state-machine fashion. A state machine enforces conditions on state transitions, which minimize the chance of bugs like these.

**Comment by kidzik** [comment]
It actually already throws "Trying to step environment which is currently done. While the monitor is active for {}, you cannot step beyond the end of an episode. Call 'env.reset()' to start the next episode.". Closing for now.
