### ISSUE TITLE
osim-rl-grader : Enforce a submit to the leaderboard on every interaction with the grader

### ISSUE THREAD

**Issue by spMohanty** [stanfordnmbl/osim-rl#57]
Given the current setup, the participants can opt to to just get their model evaluated by the server, and choose not to submit their final score. Hence bypassing the daily submission limit criteria.

I am pretty sure a lot of participants already do that.

**Comment by ctmakro** [comment]
so the final score is not counted by the server?

**Comment by spMohanty** [comment]
No, what I meant was. 
You could still run a simulation on the server, but simply avoid doing the final `client.submit()`, and count your cumulative reward yourself.

That way you can easily bypass the per day submission limits.

**Comment by LiberiFatali** [comment]
Since there is no limit on the daily submission, or I haven't seen such as rule. Is this matter?

**Comment by spMohanty** [comment]
From the POV of the grading server, there is actually a limit of max 5 submissions per day. 
I am glad no one has reached the submission limit yet, or if you do manage to "submit" more than that, maybe its a bug 😉. 

Having no limits for number of submissions per day is dangerous, as that might incentivize participants to optimise directly against the server.

**Comment by LiberiFatali** [comment]
Once I also had that idea to train the agent with the server, but I know it would be too slow  :d

**Comment by parilo** [comment]
I have no experienced with max 5 submissions while submitting 7-8 times today. I thought there is no such limit.

**Comment by spMohanty** [comment]
Fixed this with : https://github.com/spMohanty/osim-rl-grader/commit/eb35a755e6d3e0d32870ce8738b3ac691b8da767

Also deployed on the grader.

**Comment by AdamStelmaszczyk** [comment]
@spMohanty This limit of 5 is holding me back too. Could we increase it to e.g. 10?

**Comment by ctmakro** [comment]
in extremely rare situations, a single step may cost ~10 minutes. Server/Connection timeout is not uncommon.

**Comment by kidzik** [comment]
Increasing the submissions limit won't help much here -- still the objective is to reduce overfitting (at least slightly). It will be even more constrained in the second round.

Yet, indeed we will try to reduce the connection timeout error. Thanks for the reports!

**Comment by spMohanty** [comment]
@AdamStelmaszczyk : I would opt to stick to the current limit of 5 submissions a day. The server timeout indeed occurs because of certain actions which clog OpenSim and the particular step takes ages. If many participants report here on this thread that the limit of 5 is indeed restrictive because of the server timeouts, then we would be open to considering the increase of the limit.
