### ISSUE TITLE
[Hacked] show simulation on windows cloud instances thru RDP

### ISSUE THREAD

**Issue by ctmakro** [stanfordnmbl/osim-rl#59]
RDP does not support OpenGL (and most cloud machines don't have a graphic adapter capable of OpenGL2.1 or higher), so whenever you RunEnv(visualize=True), an error will be thrown. For those who want to visualize their simulation in a cloud environment, I have a solution here: https://github.com/ctmakro/stanford-osrl/blob/master/README.md#visualize-in-environments-without-a-graphic-card-ie-on-cloud

hope that helps.

**Comment by spMohanty** [comment]
Just reiterating our discussion from [crowdAI/Lobby](https://gitter.im/crowdAI/Lobby).
That mesa doesnt really help with the Broken Pipe errors (sob sob :cry: )in case of Ubuntu. 
But if it does help in case of windows servers, it could be interesting to explore if we can put the corresponding mesa related `.dlls` in the opensim conda package.

**Comment by ctmakro** [comment]
by design, simbody-visualizer.exe will dynamically call whatever openglxx.dll available. By default it will load from PATH, but if such an opengl32.dll exist in CWD, it will try the one in CWD first. This is why Mesa, as a software OpenGL implementation, works by putting dlls near executables.

**Comment by kidzik** [comment]
Thread now linked in the FAQ in readme. Closing the issue.
