### ISSUE TITLE
xlib and xcb errors

### ISSUE THREAD

**Issue by DWSimmons** [stanfordnmbl/osim-rl#67]
per the osim-rl read me, I installed the osim-rl virtualenv
I ran test.py which is nothing more than the Basic Usage from page 2 @ the nips learning to run read me from github.com/stanfordnmbl
I receive a variety of errors, none systematically reproduceable.  

1st run successful (no visualization)
simbody-visualizer: received Shutdown message. Goodbye.

2nd run hung
(opensim-rl) darin@puter:~$ Xlib:  extension "NV-GLX" missing on display "�,*".
Xlib:  extension "NV-GLX" missing on display "�,*".
Xlib:  extension "NV-GLX" missing on display "�,*".
^C

3rd run ran fine with visualization
(opensim-rl) darin@puter:~$ python test.py
Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file /home/darin/anaconda3/envs/opensim-rl/lib/python3.6/site-packages/osim/env/../models/gait9dof18musc.osim

simbody-visualizer: received Shutdown message. Goodbye.

4th, 5th, and 6th ran fine, visualization and no errors.
7th run (opensim-rl) darin@puter:~$ python test.py
Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file /home/darin/anaconda3/envs/opensim-rl/lib/python3.6/site-packages/osim/env/../models/gait9dof18musc.osim

simbody-visualizer: received Shutdown message. Goodbye.
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
simbody-visualizer: ../../src/xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.

8th run fine
9th run (opensim-rl) darin@puter:~$ python test.py
Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file /home/darin/anaconda3/envs/opensim-rl/lib/python3.6/site-packages/osim/env/../models/gait9dof18musc.osim

simbody-visualizer: received Shutdown message. Goodbye.
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
simbody-visualizer: ../../src/xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.

kernel 5.10.0-33-generic
ubuntu 17.04
nvidia gtx1080ti
nvidia-smi 381.22
AMD Ryzen 1700)
CUDA toolkit NOT installed

**Comment by DWSimmons** [comment]
installed nvidia-cuda-dev nvidia-cuda-toolkit nvidia-nsight via apt-get, set path variables, no other actions are modifications.  Errors are gone.  So, maybe it was an OpenCL thing, either way,

**Comment by DWSimmons** [comment]
and... the errors are back.  I got a new one this time.
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  4 (X_GLXDestroyContext)
  Serial number of failed request:  217
  Current serial number in output stream:  218



The errors happen at the end of the animation as if closing the stream throws the error

**Comment by kidzik** [comment]
Both errors seemed to be NVIDIA driver specific, as it was reported elsewhere, for example, here https://elrepo.org/bugs/bug_view_advanced_page.php?bug_id=610
It is very likely independent from our python environment. For the challenge, I would just suggest turning off the visualizer -- it's also much faster. For any solutions on this specific error, asking on NVIDIA specific forums might be more helpful, or https://github.com/simbody/simbody 

Sorry for the late (and unhelpful) response, I finally got some time to look deeper into this.
