### ISSUE TITLE
pelvis.x and pelvis.y are duplicated in the observation vector

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [stanfordnmbl/osim-rl#69]
pelvis.x and pelvis.y are on indices 1 and 2.

However, they are also duplicated on indices 24 and 25. 

https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/run.py#L127

To see it:

```python
env = RunEnv(visualize=False)
env.reset()
observation, reward, done, info = env.step(env.action_space.sample())
print(observation[1], observation[2])
print(observation[24], observation[25])
```

Output:
```
(0.0009060261087317481, 0.9100941208169075)
(0.0009060261087317481, 0.9100941208169075)
```

Looks like we're close to already non-backward compatible version 1.5, so maybe we can also fix this?

I'm aware that one could remove them in the client code (or keep them at the cost of redundancy), however that makes the code harder to read as it shifts the indices by 2 in the middle of a long vector. So, in one place e.g. torso.y is at index 27, in another at 25... easy to make a mistake.

**Comment by kidzik** [comment]
Thanks for bringing this out. We will fix it in the final release after the challenge. 

For now, the impact is marginal and sacrificing compatibility for shortening the observation vector wouldn't bring much value. One can simply skip the repeated values with a simple wrapper (or the controller model should quickly pick it up from the data).

Models trained in 1.4.1 should actually run on 1.5 without any modifications (as long as they give activations in [0,1]). At this point, with not too much time left, we try to change as little as possible.
