### ISSUE TITLE
Example.py: AttributeError: 'Sequential' object has no attribute 'constraints'

### ISSUE THREAD

**Issue by anthnyprschka** [stanfordnmbl/osim-rl#71]
Hi guys,
I am getting the following error when trying to run example.py:

`Traceback (most recent call last):
  File "example.py", line 82, in <module>
    agent.compile(Adam(lr=.001, clipnorm=1.), metrics=['mae'])
  File "/opensim-rl/lib/python2.7/site-packages/rl/agents/ddpg.py", line 163, in compile
    updates = actor_optimizer.get_updates(self.actor.trainable_weights, self.actor.constraints, None)
AttributeError: 'Sequential' object has no attribute 'constraints'`

Anyone know what this is about? I am using Keras==2.0.8, keras-rl==0.3.0, tensorflow==1.3.0, rl==2.4, osim-rl==1.4.1. Could it be that this was a change in Keras?

EDIT
I now noticed that the function DDPGAgent defined in the rl library takes an actor argument, for which we pass an instance of Sequential from keras.models. Then in DDPGAgent we call that Sequential's constraints attribute. But this doesn't exist. Does anyone know what this rl library is, anyways? I figure it was installed during installation of osim-rl

**Comment by anthnyprschka** [comment]
Ok completely reinstalled everything and now it works. This time it seems like i don't even have an 'rl' library. Slightly confused

**Comment by kidzik** [comment]
`rl` library is just `keras-rl' https://github.com/matthiasplappert/keras-rl/tree/master/rl
it seems it might have been some compatibility issue regarding `keras-rl`. Closing for now, thanks for reporting!

**Comment by jrao1** [comment]
It's because you were using Keras 2, which changed Sequential class plus a bunch of other things. Go back to Keras 1 would solve the issue.
