### ISSUE TITLE
Error detected by Simbody method AbstractIntegrator::takeOneStep(): Unable to advance time past 8.0694.

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [stanfordnmbl/osim-rl#72]
During the training, the episode mean reward sporadically drops down by a huge amount, because of:

```
std::exception in 'bool OpenSim::Manager::integrate(SimTK::State &)': SimTK Exception thrown at AbstractIntegratorRep.cpp:428:
  Integrator step failed at time 8.0693988624602095 apparently because:
SimTK Exception thrown at AbstractIntegratorRep.cpp:547:
  Error detected by Simbody method AbstractIntegrator::takeOneStep(): Unable to advance time past 8.0694.
  (Required condition 't1 > t0' was not met.)
```

I don't know how to reproduce this. It happened about 10 times before, in different trainings. Pointed line is [here](https://github.com/simbody/simbody/blob/3469006e99a94e9a3c7201a5308d298d20acf07f/SimTKmath/Integrators/src/AbstractIntegratorRep.cpp#L546).

**Comment by ctmakro** [comment]
this might be because of numerical problems. my experience is that if you tune the accuracy from 1e-4 to 1e-2 this will happen quite often. also, check your action values maybe?

**Comment by wjaskowski** [comment]
How can you tune the accuracy?


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by AdamStelmaszczyk** [comment]
https://github.com/ctmakro/stanford-osrl#the-simulation-is-too-slow

**Comment by wjaskowski** [comment]
Nice! How much quicker it gets?

**Comment by AdamStelmaszczyk** [comment]
Yes, it's nice finding, credit to Qin (ctmakro).

I saw speed ups from 40% to 300%, depending on the hardware and accuracy used.

Looks a bit risky though...

**Comment by AdamStelmaszczyk** [comment]
> my experience is that if you tune the accuracy from 1e-4 to 1e-2 (by changing the c source of opensim) this will happen quite often.

I checked and that looks correct. Now it's easy to reproduce: just set accuracy to e.g. 0.06 and it will raise exceptions very often.

So, looks like a bug in OpenSim. Just a thought, maybe consider a bug bounty program.

**Comment by kidzik** [comment]
That's right, this is most likely a problem on the OpenSim side (https://github.com/opensim-org/opensim-core).

**Comment by chrisdembia** [comment]
I'm not exactly sure this is a bug. Perhaps the error message is not sufficiently clear, but if you loosen the accuracy too much you won't be able to successfully simulate the system.

**Comment by kidzik** [comment]
Right, then it's just about a more appropriate error description.
