### ISSUE TITLE
Inconsistency in length of each timestep

### ISSUE THREAD

**Issue by vzhuang** [stanfordnmbl/osim-rl#73]
Under "Evaluation," 1000 iterations supposedly correspond to 5 seconds. However, later on, in the description of the OpenSim framework, it says that each timestep corresponds to 0.01 seconds. Which one is it?

**Comment by ViktorM** [comment]
1000 iterations corresponds to the 10 seconds. Info for 5 seconds I suppose should have been left from the time there were 500 iterations for the evaluation.

**Comment by kidzik** [comment]
That's right (both the question and the answer), just fixed, thank you!
