### ISSUE TITLE
Feet inside obstacle

### ISSUE THREAD

**Issue by hagrid67** [stanfordnmbl/osim-rl#76]
These images are from the same frame, just rotated round so you can see the right foot (maybe both feet) inside the obstacles (there are two overlapping ones)

![image](https://user-images.githubusercontent.com/9860840/30775486-8d57a7ee-a08c-11e7-9df6-72cca66473ff.png)

![image](https://user-images.githubusercontent.com/9860840/30775489-a39ee760-a08c-11e7-990f-468721427de2.png)

Also the left toe sphere below ground, FWIW.

![image](https://user-images.githubusercontent.com/9860840/30775509-f02e0854-a08c-11e7-85fc-a5bddf5d300c.png)

**Comment by hagrid67** [comment]
![image](https://user-images.githubusercontent.com/9860840/30775513-0a3ca67e-a08d-11e7-8e75-658de85761f3.png)

**Comment by hagrid67** [comment]
![image](https://user-images.githubusercontent.com/9860840/30775521-3e8c21ac-a08d-11e7-95ee-bd18952e89ca.png)

![image](https://user-images.githubusercontent.com/9860840/30775524-4bfffeda-a08d-11e7-878b-c8e53a3fbdc6.png)

**Comment by hagrid67** [comment]
![image](https://user-images.githubusercontent.com/9860840/30775533-741010c2-a08d-11e7-85b1-51dfdca96b9e.png)

**Comment by hagrid67** [comment]
It looks like perhaps the left foot has collided, but the right foot has entered the obstacle sphere.

**Comment by kidzik** [comment]
That's actually an expected behavior - we use balls to approximate the contact. The more the balls intersect, the larger the force. Similarly with the floor. Intuitively one can see it as a, for example, a model of a rubber ball
