### ISSUE TITLE
Joint angle missing from observation

### ISSUE THREAD

**Issue by tlbtlbtlb** [stanfordnmbl/osim-rl#77]
The coordinate is called `lumbar_extension` in the file `gait9dof18musc.osim`, and it's part of the `back` joint on the `torso` body. Adding `back` to the list of joints in `RunEnv.get_observation` would fix it.

**Comment by kidzik** [comment]
We locked this joint intentionally
https://github.com/stanfordnmbl/osim-rl/blob/master/osim/models/gait9dof18musc.osim#L1220
so it actually should be constant during the entire simulation. We will verify it though, thanks!

**Comment by tlbtlbtlb** [comment]
You're right, the value never changes from -0.139626. Thanks.
