### ISSUE TITLE
Provide / adopt common code for learning with multiple parallel environments (wishlist)

### ISSUE THREAD

**Issue by hagrid67** [stanfordnmbl/osim-rl#80]
As acknowledged in #33 and #78, the osim-rl environment is much slower (x1600)  than most of those (eg Mujoco, Atari, Bullet) in the RL literature  and a necessary part of the L2R challenge is to find a way of working with multiple parallel environments.

@ctmakro has kindly [provided](https://github.com/ctmakro/stanford-osrl) his parallel code, using a modern well-supported library Pyro4, which can be made to run across the network on commodity hardware eg AWS/EC2.

OpenAI [Baselines](https://github.com/openai/baselines) make use of MPI for parallelism, though it's not clear what effort would be required to integrate with this environment, or to run across multiple hardware.

Additional utility would come from making the parallel machinery pluggable with much faster environments, so that new learning methodology could be tested faster.  (Does this already exist?  Separate issue maybe)

Building and testing a working parallel environment setup might be better addressed collectively (ie in a open github project) than in a competition.  Once this was in place, competitors would be free to experiment with the learning / exploration methodology, rather than writing communications infrastructure and dealing with a lot of "porting".

**Comment by kidzik** [comment]
That's a great point! Our ambitious objective is to build an open-source system that outputs a robust controller for any musculoskeletal model and for any objective function. Support for parallel environment setup sounds like a great starting point. 

It's hard to predict interest after the challenge. However, there are many medical motivations of our environment, so hopefully, we can attract open-source contributions to our medical "gym".

**Comment by ViktorM** [comment]
I'd say it a must have. And can be automatically achieved by providing initial code examples with almost any of the contemporary RL libraries, the same baselines. Keral-RL library is not maintaned and supported for a few years. And for all of the contemporary RL libraries support of distributed training is a de facto standart.

**Comment by kidzik** [comment]
Two top teams provided their parallel implementations (one of them put two implementations)
http://osim-rl.stanford.edu/docs/nips2017/solutions/
These implementations can be easily adapted to any OpenSim environment.

Nevertheless, we would greatly benefit from a dedicated solution -- we welcome contributions on that!

**Comment by ViktorM** [comment]
@kidzik as I've noticed that in examples in under construction section baseline's based code RL samples. That's what I meant - to adapt some more modern RL library instead of Keras_RL and it's almost there. May be hagrid67 asked for something more, but I'm happy with the current progress.

**Comment by hagrid67** [comment]
FWIW I think the [ray-project](https://github.com/ray-project) seems to meet this need now, with lots of different RL algos like PPO, DDPG, IMPALA implemented (in RLLib in the same project) without using MPI.  It supports clusters nicely and is currently very active.
