### ISSUE TITLE
importing opensim can't find libquadmath.so.0

### ISSUE THREAD

**Issue by kirk86** [stanfordnmbl/osim-rl#81]
Hi everyone,
I've been having some difficulty importing opensim.
After following all the steps and installing opensim from conda distribution.
When I drop into an ipython console and `import opensim` I get the following error:
```
ImportError: libquadmath.so.0: cannot open shared object file: No such file or directory
```
Any ideas how to mitigate this?

**Comment by kirk86** [comment]
Just to add some more details regarding my situation.
Searching I came across this thing
```
The GCC Quad-Precision Math library (libquadmath) is included in GCC 4.6 and later, but CentOS 6 uses GCC 4.4. Your best alternative is to use another Linux distribution to run that software.
```

The problem that I'm facing is that this is a CentOS server in which I don't have administrative rights. Is there any way to overcome this issue?

**Comment by kirk86** [comment]
I installed 
`libgcc 5.2.0`
`gcc 4.8.5-7`
from conda and now I'm getting the following error:
```
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/user/miniconda2/envs/opensim-env/lib/python2.7/site-packages/opensim/_simbody.so)
```

**Comment by chrisdembia** [comment]
I'm not sure what's going on but you might need to tweak your LD_LIBRARY_PATH so that conda's libraries are found instead. This link may be helpful: https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=7165&p=0&start=10&view=&sid=0c8cf01459c3d937ad909988ca517207

**Comment by kirk86** [comment]
@chrisdembia thanks just before I saw your message I did added in `.bashrc`, `LD_LIBRARY` and appended to it the location of lib folder in the miniconda evironment containing the `libquadmath.so.0` file. But now things are worst than before. Any previous terminal commands like `vim`, `ls -la` don't work they all throw a segmentation core dumped error. And the funny thing is that now I can't even access my `.bashrc` to remove that appended binary from `LD_LIBRARY` so I'm stuck. Any ideas?

**Comment by chrisdembia** [comment]
Oh no!!

What about `mv`? Can you `mv ~/.bashrc ~/.bashrc_backup`? On Ubuntu, you can enter commands via `Alt + F2`; does that work on CentOS? How about entering a different shell that doesn't read `.bashrc` like the fish shell? Do you have another OS on the machine that you could use to move the bashrc file?

After you regain control of your system, consider using LD_PRELOAD instead of setting LD_LIBRARY_PATH (e.g., `LD_PRELOAD=/path/to/conda/libc.so.# python -c "import opensim"`)

**Comment by chrisdembia** [comment]
Also, consider using python to move the bashrc file, if you're able to enter Anaconda's python interpreter.

**Comment by kirk86** [comment]
@chrisdembia  thanks for the advice but nothing works
Anything I've tried results in `Segmentation fault (core dumped)`
Entering python or ipython the same thing.
`mv` command not working the same 
The only command that seems to be working is `pwd`.
The problem is that this is a cluster machine. So I only have sh access. Can't do `Alt + F2` either.
I've tried executing `./bin/sh` but it says that it cannot find the file even `./usr/bin/sh` gives the same result.

**Comment by chrisdembia** [comment]
You could ask the cluster admin to edit your bashrc.

You could try running `LD_PRELOAD=/path/to/original/libc mv ...`.

**Comment by kirk86** [comment]
@chrisdembia 

> You could ask the cluster admin to edit your bashrc.
> 
yeah that's the overall idea
> You could try running LD_PRELOAD=/path/to/original/libc mv ....

Sorry could you elaborate a bit on this one. Do you mean I should run the above command in the terminal? What about `mv ...` what is that for?

**Comment by chrisdembia** [comment]
You can use LD_PRELOAD to override the libraries that get loaded. So if you're trying to run a command that's not working normally, you can set the LD_PRELOAD environment variable for that command. In general, if you want to set an environment variable value for 1 command, you can use `VARNAME=varvalue command`.

So I'm thinking you could use `LD_PRELOAD=/usr/lib/libc.so.6 mv ~/.bashrc ~/.bashrcbackup`.

**Comment by kirk86** [comment]
@chrisdembia 
this what I get
```
mv: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/jmitro/miniconda2/envs/glib/lib/librt.so.1)
mv: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/jmitro/miniconda2/envs/glib/lib/libpthread.so.0)
```

**Comment by kirk86** [comment]
@chrisdembia thanks for your help.
Finally I managed to resolve it in the following way
`ssh -t user@host dash`
edit the `.bashrc`
and now everything is as it used to be. I'm gonna close this for the moment.
I'm gonna try to load the `libmathquad` through `LD_PRELOAD` and inform back if I see any errors.

**Comment by chrisdembia** [comment]
Cool.

**Comment by kirk86** [comment]
Now the problem is the following error
`import opensim`

`ImportError: /lib64/libc.so.6: version  GLIBC_2.14 not found (required by /home/user/miniconda2/envs/opensim-env/lib/python2.7/site-packages/opensim/_simbody.so)`

I tried adding to the `LD_PRELOAD` the `libc.so.6` from the conda environment. I had more than one
