### ISSUE TITLE
Other obstacles and clarification of (ilio)psoas?

### ISSUE THREAD

**Issue by HaoshengZou** [stanfordnmbl/osim-rl#82]
I actually have two questions:

1. The first few sentences of this challenge state that
> Potential obstacles include external obstacles like steps, or a slippery floor, along with internal obstacles like muscle weakness or motor noise.

But it seems for now only balls and muscle weakness exist as obstacles. Even in the new `difficulty = 3` case, there're just more balls. So will there be steps, slippery floor and motor noise? Or they're already present and I just missed them...

2. I'm not very familiar with biomechanics. Does psoas and iliopsoas refer to the same thing in this competition?
Observation includes the randomized strength of left and right psoas. Action includes the activation of the left and right iliopsoas. Are they the same?

**Comment by kidzik** [comment]
1. We will keep `difficulty = 2` for the second round and there will be no extra obstacles (just the balls and variable muscle strength already present in `difficulty = 2`. "steps, or a slippery floor," are just the remainings on the very early stage of development, sorry for the confusion.

2. Yes, they are the same in our model.

**Comment by kidzik** [comment]
More details on muscles will appear in the paper in a week or two. Regarding the obstacles, we won't have them (most likely) in the new challenge. The old environment will be still accessible, but not maintained.
