### ISSUE TITLE
Update on leaderboard after the new version 1.5

### ISSUE THREAD

**Issue by LinZichuan** [stanfordnmbl/osim-rl#85]
I am confused whether the submissions before version 1.5 on the learderboard are still valid.

**Comment by AdamStelmaszczyk** [comment]
Yep, now no participant knows which are valid and which are not.

Related discussion in the end of https://github.com/stanfordnmbl/osim-rl/issues/64.

**Comment by kidzik** [comment]
Right, that is an unfortunate consequence of the last bugfix (we can't check retrospectively which of the solutions were submitted with [0,1] activations. Therefore, we increased the number of spots in the second round (we planned 10 spots, now it's everyone with at least 15 points). The second round will be run in the 1.5 environments.

**Comment by AdamStelmaszczyk** [comment]
Oh, I thought you were persisting the actions into some database. Thought that it was useful for generating visualizations and reproducing problems (e.g. the one when OpenSim gets very slow on some steps or submit failures/continuations). Possibly a good thing to have in the future.

**Comment by kidzik** [comment]
We have them for most of the submissions but not all of them. At the beginning it was used only for recreating the videos -- we haven't anticipated how useful it might be in other scenarios. Now we know :)
