### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gautam1858** [stanfordnmbl/osim-rl#95]
Hi, 
    When I try to install I am getting this error
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - opensim -> python=2.7
  - python=3.6
```
I guess there is no version of opensim 3.6 for macOS. Reference https://anaconda.org/kidzik/opensim/files

**Comment by gautam1858** [comment]
I guess you have missed the Mac version of 3.6 here https://anaconda.org/kidzik/opensim/files :)

**Comment by gautam1858** [comment]
I guess there is no version of opensim 3.6 Mac. Reference https://anaconda.org/kidzik/opensim/files

**Comment by spMohanty** [comment]
Hi @gautam1858 ,

The 3.6 reference is for python version 3.6, and we do have a build for Mac osx 64, py3.6 ( linux-64/opensim-4.0.0-py36_17.tar.bz2).

Looking at your errors, it seems that the opensim package that your conda env is picking up has been built for python2.7, and then there a python3.6 installation that you want to go through, leading to a conflict.

Can you please try with a fresh conda environment ? 
```bash
conda create -n opensim-rl_gautam1858 -c kidzik opensim git python=3.6
source activate opensim-rl_gautam1858

conda install -c conda-forge lapack git
pip install git+https://github.com/stanfordnmbl/osim-rl.git

python -c "import opensim"
```

**Comment by gautam1858** [comment]
Hi @spMohanty tried but not working, in your comment you are mentioning "linux-64/opensim-4.0.0-py36_17.tar.bz2" which is for linux but I am using macOS and in this URL you don't have 3.6 support version for Mac

**Comment by spMohanty** [comment]
Ahh, you are right ! Sorry my bad !
The py36 versions are built just for macosx64.
Here is the discussion around this issue : https://github.com/stanfordnmbl/osim-rl/issues/16

We will try to release built binaries for macosx64 and py36 before the launch of the nips2018 challenge. 
In the meantime, please use the py27 version.

**Comment by gautam1858** [comment]
@spMohanty The Mac version of anaconda py2.7 has no no attribute 'setIntegratorAccuracy'
so getting some errors, is it possible to kindle release the Mac version, tried using the staged recipes but getting some errors

**Comment by kidzik** [comment]
Which errors are you getting? The recipe that worked for linux should build for os x as well. There are some differences in paths but thats already taken care of in the script

**Comment by kidzik** [comment]
You said that you "tried using the staged recipes but getting some errors", I'm happy to help with building the package, just please let me know what errors you got. Otherwise you can either use docker and ubuntu or you can wait for the release of the mac version (we should have it in 2-3 weeks).

Yes, right now on conda there is no mac build with python 3.6 and with `setIntegratorAccuracy` property.

**Comment by gautam1858** [comment]
Hi, so my build.sh file is 
`#!/bin/bash

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

# TODO: Dependencies should be separate packages...
mkdir opensim_dependencies_build
cd opensim_dependencies_build
cmake ../dependencies/ \
      -DCMAKE_INSTALL_PREFIX="$PREFIX" \
      -DCMAKE_BUILD_TYPE=Release
make -j8
cd ..

cp -r $PREFIX/BTK/lib/btk-0.4dev/* $PREFIX/lib/
cp -r $PREFIX/simbody/libexec/simbody/* $PREFIX/bin/

# TODO: Tests are missing!
mkdir opensim_build
cd opensim_build
cmake ../ \
      -DCMAKE_INSTALL_PREFIX="$PREFIX" \
      -DCMAKE_BUILD_TYPE=Release \
      -DOPENSIM_DEPENDENCIES_DIR="$PREFIX" \
      -DBUILD_PYTHON_WRAPPING=ON \
      -DBUILD_JAVA_WRAPPING=OFF \
      -DPYTHON_VERSION_MAJOR=3 \
      -DPYTHON_VERSION_MINOR=6 \
      -DWITH_BTK=ON
make -j8
make install
`
My meta.yml file

`package:
    name: opensim
    version: "4.0.0"

#source:
#    fn: OpenSim-40-source.zip
#    url: https://github.com/opensim-org/opensim-core/archive/v4.0.0_alpha.zip
#    sha256: dd425e886f394098533142652e246b375c8fb4d69246f0ffffcdd63bbbdb39c3

source:
#    path: /home/kidzik/workspace/opensim-core
    git_url: https://github.com/opensim-org/opensim-core.git
    git_rev: 399c8d57a779dd5dde2916192f8b92bfc959e269 #beta
  
build:
    number: 12
    # NOTE : For C++11 builds, vc14/VS 2015 are the only acceptable targets
    # which only Python 3.5 supports. So skip previous Python versions.
    # skip: true                # [win and not py35]
    features:
        - vc14                # [win and py35]
    # NOTE : This is needed to ensure the paths to Simbody's binaries, like
    # simbody-visualizer, are corrected.
    detect_binary_files_with_prefix: true

requirements:
  run:
        - python >=3.6
        - openblas
        - freeglut
  build:
        - swig
        - toolchain
        - cmake >=2.8.6
        - python >=3.6
        # - python                  # [win]
`
And bad.dat

`mkdir opensim_dependencies_build
cd .\opensim_dependencies_build
cmake ..\dependencies^
	-G"Visual Studio 14 2015 Win64"^
	-DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%"
cmake --build . --config Release -- /maxcpucount:8
cd .. 

mkdir opensim_build
cd .\opensim_build
cmake ..\^
	-G"Visual Studio 14 2015 Win64"^
	-DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%"^
	-DOPENSIM_DEPENDENCIES_DIR="%LIBRARY_PREFIX%"^
	-DBUILD_PYTHON_WRAPPING=ON^
	-DWITH_BTK=ON
cmake --build . --target install --config Release -- /maxcpucount:8

cp %LIBRARY_PREFIX%\simbody\bin\simbody-visualizer.exe %PREFIX%\simbody-visualizer.exe
cd %LIBRARY_PREFIX%\sdk\python
python setup.py install
`
And I am getting error when I run this

**Comment by kidzik** [comment]
Have you tried this?
```
git clone https://github.com/stanfordnmbl/staged-recipes.git
cd staged-recipes/recipes/
conda build opensim --python=3.5
```
What errors are you getting?

**Comment by gautam1858** [comment]
@kidzik 

I started using linkup but following are the errors that I am getting for Mac, when I try to build it 

`
  File "/Users/neutrino/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
    verify=args.verify)
  File "/Users/neutrino/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/Users/neutrino/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1776, in build_tree
    notest=notest,
  File "/Users/neutrino/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 995, in build
    raise e
  File "/Users/neutrino/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 986, in build
    channel_urls=tuple(m.config.channel_urls))
  File "/Users/neutrino/anaconda3/lib/python3.6/site-packages/conda_build/environ.py", line 682, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: ['freeglut']
`

**Comment by kidzik** [comment]
Thank you @gautam1858 , I'll be trying to build for OS X tonight, let me see if I run into this issue.

**Comment by kidzik** [comment]
I recompiled the OS X version a few days ago and it is available in conda right now.
    conda create -n opensim-rl -c kidzik opensim python=3.6.1
