### ISSUE TITLE
ImportError: cannot import name RunEnv     in Mac OSX 

### ISSUE THREAD

**Issue by akhilsanand** [stanfordnmbl/osim-rl#98]
Hello,

I am new to osim-rl, I have followed the installation step with python 2.7 version in Mac OSX as I could not do it with python 3.6 version. When I try to run the basic usage to execute 200 iterations it throws the error "ImportError: cannot import name RunEnv".

Please help to solve the issue.

![screen shot 2018-04-19 at 3 49 34 pm](https://user-images.githubusercontent.com/38490368/38995490-4c452640-43e9-11e8-81a6-8c32907e74d3.png)

Regards,
Akhil

**Comment by kidzik** [comment]
Please use branch `ver1.5.5` (https://github.com/stanfordnmbl/osim-rl/tree/ver1.5.5), the current `master` branch is under construction for the NIPS 2018 challenge.

**Comment by akhilsanand** [comment]
Hello Lukasz,

Thanks for the reply,
I tried 2017 branch, but still the same error persists. Any other alternatives?

Regards,
Akhil

**Comment by akhilsanand** [comment]
Hello Lukasz,

It works, I did not do the installation right last time.

Thanks 
Akhil
