### ISSUE TITLE
confusion in script/example.py

### ISSUE THREAD

**Issue by leejk526** [stanfordnmbl/osim-rl#99]
Hi,
I've done in 'ver1.5.5'.
I'm trying to run "scripts/example.py" code for training with command "python scripts/example.py --visualize --train --model sample"

But, the interpreter said,
![2018-04-22 4 17 12](https://user-images.githubusercontent.com/13674609/39092426-a2373b2c-4648-11e8-8e03-b7805c86abc2.png)

So, I wondered that where is "osim/env/*" path.
When I tried that,
![2018-04-22 4 18 45](https://user-images.githubusercontent.com/13674609/39092437-df8d539e-4648-11e8-8fed-839417130b34.png)

osim path is in virtual python root library path, not the "$osim-rl/osim/env" path.
 I annotated "import opensim as osim" in the "scripts/example.py" file like this.
![2018-04-22 4 24 43](https://user-images.githubusercontent.com/13674609/39092481-b19d3c64-4649-11e8-8f00-ac0270e839da.png)

Am I right? 
My primary question is a confusion of the real path 'osim/env'.
why does the editor write "import opensim as osim"?

Thank you for reading.

**Comment by kidzik** [comment]
Yes you are right. `opensim` package is actual OpenSim simulator, while the reinforcement learning package is called `osim`. Therefore `import opensim as osim` is not only confusing but just wrong. It was there in the old script from the times we were starting to build this environment. Thanks for the catch!

The script is now here https://github.com/stanfordnmbl/osim-rl/blob/master/examples/ddpg.keras-rl.py

**Comment by leejk526** [comment]
Thank you for response!
